// Optional local software UI test; Playwright is a test-only dependency, not shipped to browsers.
import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:4173';const out=process.env.QA_OUTPUT||'/tmp/gradcompass-qa';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});const checks=[];const check=(name,condition)=>{assert(condition,name);checks.push({name,passed:true});};
try{
 await page.goto(base);await page.waitForSelector('.advisor-card');check('default count 46 opportunities',await page.locator('.advisor-card').count()===46);check('first result in initial viewport',(await page.locator('.advisor-card').first().boundingBox()).y<850);await page.screenshot({path:`${out}/desktop.png`,fullPage:false});
 await page.locator('#search').fill('Xihui');check('search narrows results',await page.locator('.advisor-card').count()===1);await page.locator('[data-detail]').first().click();await page.waitForSelector('#detail-dialog[open]');check('detail source and requirement readable',(await page.locator('#detail-content').innerText()).includes('high honors')||(await page.locator('#detail-content').innerText()).includes('本科'));check('detail has safe source links',await page.locator('#detail-dialog a[target="_blank"][rel="noopener noreferrer"]').count()>0);await page.screenshot({path:`${out}/detail.png`,fullPage:false});await page.keyboard.press('Escape');check('Escape dismisses detail',!(await page.locator('#detail-dialog').isVisible()));
 await page.locator('#reset-filters').click();check('eligibility toggle removed',await page.locator('#eligible-only').count()===0);await page.locator('#opportunity-filter').selectOption('RA');check('RA opportunity count differs from advisor count',(await page.locator('#result-count').innerText())==='2 条机会 · 1 位导师');await page.locator('[data-detail]').first().click();check('RA work permit and unknown time disclosed',(await page.locator('#detail-content').innerText()).includes('工作许可未核实')&&(await page.locator('#detail-content').innerText()).includes('截止时刻：未公布'));await page.keyboard.press('Escape');await page.locator('#reset-filters').click();
 await page.locator('#institution-filter').selectOption('HKUST');check('institution filter exact',await page.locator('.advisor-card').count()===5);await page.locator('#reset-filters').click();await page.locator('#opportunity-filter').selectOption('MPhil');check('degree filter narrows results',await page.locator('.advisor-card').count()<30);await page.locator('#reset-filters').click();
 for(let i=0;i<3;i++)await page.locator('[data-compare]').nth(i).click();await page.locator('[data-compare]').nth(3).click();check('compare capped at three',(await page.locator('#compare-count').innerText()).includes('3 / 3'));await page.locator('#compare-open').click();check('comparison includes three columns',await page.locator('.compare-column').count()===3);await page.screenshot({path:`${out}/compare.png`,fullPage:false});await page.locator('[data-close="compare-dialog"]').click();await page.locator('#compare-clear').click();check('clear removes tray',!(await page.locator('#compare-tray').isVisible()));
 await page.locator('nav [data-view="deadlines"]').click();check('deadlines view has expired notice',(await page.locator('#view-content').innerText()).includes('已截止'));await page.locator('nav [data-view="materials"]').click();check('material requirement rendered',(await page.locator('#view-content').innerText()).includes('至少 2'));await page.locator('.source-nav').click();check('daily status honest',(await page.locator('#view-content').innerText()).includes('每日检查已启用 · 首轮待验证'));await page.goBack();check('back navigation restores material view',(await page.locator('#results-title').innerText())==='材料要求');
 await page.locator('nav [data-view="advisors"]').click();await page.locator('#search').fill('zero-nonexistent-name');check('empty state useful',(await page.locator('#view-content').innerText()).includes('没有同时满足'));await page.locator('[data-reset]').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/mobile.png`,fullPage:false});check('mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check('mobile first result within first screen',(await page.locator('.advisor-card').first().boundingBox()).y<844);await page.locator('[data-detail]').first().click();check('mobile dialog no overflow',await page.evaluate(()=>{let d=document.querySelector('dialog[open]');return d.scrollWidth<=d.clientWidth+1;}));await page.keyboard.press('Escape');
 await page.setViewportSize({width:768,height:1024});check('tablet no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:320,height:850});check('narrow mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 check('no runtime or CSP errors',errors.length===0);fs.writeFileSync(`${out}/browser-report.json`,JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
}finally{await browser.close();}
