import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {deadlineStatus,filterDeadlines} from '../assets/core.js';import {renderRecordSummary} from '../assets/record-summaries.js';
import {normalizeMaterialSupplement} from '../assets/material-supplement.js';
const read=name=>JSON.parse(fs.readFileSync(new URL('../data/'+name,import.meta.url),'utf8'));const catalog=read('catalog.json');const materials=read('material-summaries.json');
test('CityU ordinary cycle correction is limited to two routes and one deadline',()=>{const changed=catalog.routes.filter(r=>r.cycleReview&&r.institution==='CityUHK');assert.deepEqual(changed.map(r=>r.id),['cityu_me_rpg-mphil','cityu_me_rpg-phd']);for(const r of changed){assert.equal(r.cycle2027Verified,false);assert.equal(r.status,'verified');assert.equal(r.bachelorEligible,true);assert.equal(r.noMasterRequired,true);assert.equal(r.checkedDate,'2026-10-01');assert.equal(r.sourceRecord.checked_at,'2026-10-01');assert.equal(r.cycleReview.checkedDate,'2026-10-02');assert(r.admissionYear.includes('尚待确认'));assert(!r.admissionYear.includes('2026-12-01'));}assert.equal(catalog.deadlines.filter(r=>r.cycleReview&&r.institution==='CityUHK').length,1);});
test('ordinary calendar no longer presents HKPFS deadline or a fabricated time',()=>{const d=catalog.deadlines.find(d=>d.id==='cityu_me_rpg-main');assert.equal(d.date,null);assert.equal(d.dateStatus,'unknown');assert.equal(d.status,'unknown');assert.equal(d.checkedDate,'2026-10-01');assert.equal(deadlineStatus(d,catalog.metadata.checkedDate),'unknown');assert(filterDeadlines(catalog).some(x=>x.id===d.id));const h=renderRecordSummary('deadline',d,catalog).html;assert(h.includes('截止日期待确认'));assert(h.includes('截止时刻</dt><dd>待复核（来源版本不一致）'));assert(h.includes('截止日期</dt><dd>待复核（来源版本不一致）'));assert(!h.includes('截止日期</dt><dd>未公布')); assert(h.includes('批次复核于 2026-10-02'));assert(h.includes('来源版本冲突'));assert(h.includes('不据此推定普通轮')); assert(!h.includes('截止日期</dt><dd>2026-12-01'));});
test('both CityU material deadline statements remain unknown for ordinary routes and separate HKPFS',()=>{const rows=normalizeMaterialSupplement(materials,catalog).filter(r=>r.cycleReview&&r.institution==='CityUHK');assert.equal(rows.length,2);for(const r of rows){const d=r.requirements.find(x=>x.kind==='deadline');assert.equal(d.requirementStatus,'unknown');assert(d.text.includes('普通 MPhil／非 HKPFS PhD'));assert(d.text.includes('RGC 初步登记 2026-12-01 12:00'));assert(d.text.includes('CityUHK 完整申请同日 23:59'));assert.equal(r.checkedDate,'2026-10-01');assert.equal(r.cycleReview.checkedDate,'2026-10-02');const h=renderRecordSummary('material',r,catalog).html;assert(h.includes('申请日期 · 待确认'));assert(h.includes('批次复核说明'));}});
test('CityU material records preserve the previously reviewed unknown ordinary deadlines exactly',()=>{const rows=materials.records.filter(r=>r.institution==='CityUHK');assert.equal(crypto.createHash('sha256').update(JSON.stringify(rows)).digest('hex'),'bd15e99305076ff4b9d25e8103f86293c0b59dfede90b7f3a320efe4f230ccb8');});
test('historical catalog validation is clearly distinguished from the cycle-reviewed current bytes',()=>{const manifest=read('catalog-test-manifest.json');assert.equal(manifest.sha256,'094e513c0a2120bb2bee44efda475e2800537bcba797468add44bf5a479bd605');assert(manifest.scope.includes('Historical'));assert.equal(manifest.currentIdentityReview.catalogSha256,crypto.createHash('sha256').update(fs.readFileSync(new URL('../data/catalog.json',import.meta.url))).digest('hex'));});
