import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {escapeHTML,safeUrl,textValue,isVerifiedRoute,routesFor,hasVerifiedPath,themesFor,filterAdvisors,filterRoutes,filterDeadlines,deadlineStatus,toggleCompare} from '../assets/core.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));
test('public baseline excludes unknown and excluded routes',()=>{const rows=filterAdvisors(catalog);assert.equal(rows.length,30);assert(rows.every(a=>a.eligibility==='verified'&&hasVerifiedPath(a,catalog)));assert(!rows.some(a=>/zhongyu|yaran/i.test(a.id)));});
test('default collection conditions cannot be disabled by stale filter state',()=>{const rows=filterAdvisors(catalog,{eligibleOnly:false});assert.equal(rows.length,30);assert(!rows.some(a=>a.eligibility!=='verified'));});
test('default route predicate requires all three prerequisites',()=>{assert(!isVerifiedRoute({status:'verified',bachelorEligible:true,noTuimianRequired:null,noMasterRequired:true}));assert(filterRoutes(catalog).every(r=>r.bachelorEligible&&r.noTuimianRequired&&r.noMasterRequired));});
test('institution filter keeps Hong Kong and mainland campuses distinct',()=>{const hk=filterAdvisors(catalog,{institution:'HKUST'});assert.equal(hk.length,5);assert(hk.every(a=>a.institution==='HKUST'));const schools=new Set(catalog.advisors.map(a=>a.institution));assert(schools.has('HKUST'));assert([...schools].some(s=>s.includes('GZ')));assert(schools.has('CUHK'));assert([...schools].some(s=>/Shenzhen|SZ/i.test(s)));});
test('search is case-insensitive and supports Chinese names',()=>{assert(filterAdvisors(catalog,{query:'xihui'}).some(a=>a.name==='Xihui Liu'));assert(filterAdvisors(catalog,{query:'刘希慧'}).some(a=>a.name==='Xihui Liu'));assert.equal(filterAdvisors(catalog,{query:'aNameNotPresent987'}).length,0);});
test('degree filtering cannot infer MPhil from PhD',()=>{const mphil=filterAdvisors(catalog,{degree:'MPhil'});assert(mphil.every(a=>routesFor(a,catalog).some(r=>r.degree==='MPhil'&&isVerifiedRoute(r))));const yin=catalog.advisors.find(a=>/peng.yin|yin.peng/i.test(a.id));if(yin)assert(!mphil.includes(yin));});
test('theme filter uses research evidence and explicit opening filter stays separate',()=>{const rows=filterAdvisors(catalog,{topic:'移动操作',opening:'explicit'});assert(rows.length>0);assert(rows.every(a=>themesFor(a).includes('移动操作')&&a.opening==='explicit'));});
test('future published deadline does not imply application is open',()=>{assert.equal(deadlineStatus({date:'2027-06-01',status:'unknown'}),'unknown');assert.equal(deadlineStatus({date:'2026-09-30',status:'open'}),'expired');assert.equal(deadlineStatus({date:null,status:'unknown'}),'unknown');assert(catalog.deadlines.some(d=>deadlineStatus(d)==='expired'));});
test('deadline filter matches the chosen institution and verified routes',()=>{const rows=filterDeadlines(catalog,{institution:'HKUST'});assert(rows.length>0);assert(rows.every(d=>d.institution==='HKUST'));});
test('compare supports remove and max three profiles',()=>{assert.deepEqual(toggleCompare(['a','b'],'a'),['b']);const arr=['a','b','c'];assert.equal(toggleCompare(arr,'d'),arr);assert.deepEqual(toggleCompare(['a'],'b'),['a','b']);});
test('untrusted source text and URLs are escaped',()=>{assert.equal(safeUrl('javascript:alert(1)'),null);assert.equal(safeUrl('data:text/html,evil'),null);assert.equal(safeUrl('https://example.edu/path'),'https://example.edu/path');assert.equal(escapeHTML('<img src=x onerror="bad">'), '&lt;img src=x onerror=&quot;bad&quot;&gt;');assert.equal(textValue({text:'Actual requirement',sources:[]}), 'Actual requirement');});
test('catalog references resolve and original source metadata is retained',()=>{const ids=new Set(catalog.routes.map(r=>r.id));for(const a of catalog.advisors){assert(a.routeIds.every(id=>ids.has(id)));assert(a.sources.length);assert(a.checkedDate==='2026-10-01');}assert.equal(catalog.metadata.sourceInputs.length,3);assert.equal(catalog.metadata.dailyUpdatesEnabled,false);});
test('no personal background or private fit copied into public catalog',()=>{const str=JSON.stringify(catalog);for(const s of ['private_fit','fit_priority','research_overlap_assessment','user_gpa','user_background','personal_strategy'])assert(!str.includes(s),s);});
test('static page has accessibility fundamentals and strict CSP',()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert(html.includes('lang="zh-CN"'));assert(html.includes('class="skip-link"'));assert(html.includes('aria-live="polite"'));assert(html.includes('aria-labelledby="detail-title"'));assert(html.includes('Content-Security-Policy'));assert(!html.includes('style='));const css=fs.readFileSync(new URL('../assets/style.css',import.meta.url),'utf8');assert(css.includes('prefers-reduced-motion'));assert(css.includes(':focus-visible'));assert(css.includes('min-height:44px'));});

test('degree-specific opening filter cannot borrow PhD or RA signals for MPhil',()=>{const rows=filterAdvisors(catalog,{degree:'MPhil',opening:'explicit'});assert(!rows.some(a=>a.id==='hku-xihui-liu'));assert(rows.every(a=>a.openingDetails.some(o=>o.degree==='MPhil'&&o.status==='explicit')));});
