import {maintenanceBaseline} from './maintenance-baseline.mjs';
import {recruitmentBaseline,recruitmentBaselineText} from './recruitment-baseline.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {normalizeMaterialSupplement} from '../assets/material-supplement.js';import {renderRecordSummary} from '../assets/record-summaries.js';import {filterRoutes,filterDeadlines,deadlineStatus} from '../assets/core.js';
const read=n=>JSON.parse(fs.readFileSync(new URL('../data/'+n,import.meta.url),'utf8'));const c=read('catalog.json'),m=maintenanceBaseline(read('material-summaries.json'));const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const d=id=>c.deadlines.find(x=>x.id===id);const route=id=>c.routes.find(x=>x.id===id);
test('targeted cycle review retains original route inputs, all eligibility and uninvolved advisor records',()=>{assert.equal(hash(maintenanceBaseline(c).routes.map(r=>r.sourceRecord??null)),'6a23580c0196a59eb261908aaf20582f1b9c9090e7b43f43e5fa794a04bbf6a4');assert.equal(hash(recruitmentBaseline(c).advisors.filter(a=>!['hkust-yajing-shen','polyu_pai_zheng'].includes(a.id)).map(a=>{if(a.id!=='westlake-kaicheng-yu')return a;const restored=structuredClone(a);restored.nameZh='余开程';delete restored.identityReview;return restored})),'a7d854de406f57000f3901c90589807fbec4df001b8c95383f309ebb4249adc2');assert.equal(filterRoutes(c).length,28);assert.equal(c.metadata.checkedDate,'2026-10-01');for(const r of c.routes.filter(r=>r.cycleReview&&r.institution!=='CityUHK')){assert.equal(r.checkedDate,'2026-10-01');assert.equal(r.cycleReview.checkedDate,'2026-10-02');assert.equal(r.applicationStatus,'unknown');}});
test('HKU main and conditional clearing deadlines use explicit HKT and correct admission year',()=>{for(const [id,date]of [['hku-cycle','2026-12-01'],['hku-2027-first-clearing','2027-04-30'],['hku-2027-second-clearing','2027-08-31']]){assert.equal(d(id).date,date);assert.equal(d(id).deadlineTime,'23:59');assert.equal(d(id).timezone,'Asia/Hong_Kong');assert.equal(d(id).routeIds.length,4);assert.equal(d(id).status,'unknown');}assert.match(d('hku-2027-first-clearing').note,/仍有名额/);assert.match(d('hku-2027-second-clearing').note,/2027-05-01/);});
test('HKBU ordinary deadlines have no invented time or timezone and are not early or scholarship rounds',()=>{for(const [id,date]of [['hkbu-rpg-2027-first-deadline','2026-12-01'],['hkbu-rpg-2027-second-deadline','2027-04-15']]){const r=d(id);assert.equal(r.date,date);assert.equal(r.deadlineTime,null);assert.equal(r.timezone,null);assert.match(r.note,/普通轮.*HKPFS.*提前招生/);assert(r.routeIds.includes('hkbu_cs_rpg-mphil'));}assert.equal(route('hkbu_cs_rpg-phd').cycle2027Verified,true);});
test('Red Bird and Guangzhou doctoral applicant categories keep their independent exact dates',()=>{assert.equal(d('redbird-cycle').date,'2027-03-01');assert.equal(d('redbird-cycle').deadlineTime,'23:59');assert.equal(d('redbird-cycle').timezone,null);assert.match(d('redbird-cycle').note,/2028 Fall/);for(const [id,date]of [['hkust-gz-phd-2027-fall-international-deadline','2027-06-15'],['hkust-gz-phd-2027-fall-chinese-deadline','2027-07-15']]){const r=d(id);assert.equal(r.date,date);assert.equal(r.deadlineTime,'23:59');assert.equal(r.timezone,'Asia/Shanghai');assert.equal(r.routeIds.length,3);assert(!r.routeIds.includes('hkust-gz-rbm'));}});
test('CUHK Shenzhen actual programme spring and autumn deadlines remain separate with resolved retrieval history',()=>{assert.equal(d('cuhksz-cycle').date,'2026-10-31');assert.equal(d('cuhksz-ai-2027-fall-deadline').date,'2027-05-31');for(const id of ['cuhksz-cycle','cuhksz-ai-2027-fall-deadline']){assert.equal(d(id).deadlineTime,null);assert.equal(d(id).timezone,null);assert.match(d(id).note,/滚动招生.*满额即止/);}assert.match(route('cuhksz-ai-phd').cycleReview.retrievalConflict.resolution,/Current official.*confirms 2027/);});
test('material maintenance alters only Guangzhou cycle text while other records and all non-deadline requirements remain unchanged',()=>{assert.equal(m.sources.length,38);assert.equal(hash(m.records.filter(r=>!['hkust-gz-rbm-materials','hkust-gz-phd-materials'].includes(r.id))),'2f65e3e68c9059ffb8166e43b0db876d2858f6d2663843e5746b0cf322c49b64');assert.equal(hash(m.records.map(r=>r.requirements.filter(q=>q.kind!=='deadline'))),'e7fa66846f073c13466109ede56fb592d363a34c172434acb296c91b28febf58');const rows=normalizeMaterialSupplement(m,c);assert.equal(rows.length,12);for(const id of ['hkust-gz-rbm-materials','hkust-gz-phd-materials']){const r=rows.find(r=>r.id===id);assert.equal(r.checkedDate,'2026-10-01');assert.equal(r.cycleReview.checkedDate,'2026-10-02');assert(renderRecordSummary('material',r,c).html.includes('批次复核说明'));}});
test('deadline status remains independent from future dates and links resolve only to verified current routes',()=>{assert.equal(c.deadlines.length,21);for(const r of c.deadlines){for(const id of r.routeIds)assert(filterRoutes(c).some(x=>x.id===id));if(r.checkedDate==='2026-10-02'){assert.equal(r.status,'unknown');assert.equal(deadlineStatus(r,c.metadata.checkedDate),'unknown');const html=renderRecordSummary('deadline',r,c).html;assert(html.includes(r.date));assert(!html.includes('undefined'));}}assert.equal(filterDeadlines(c,{institution:'HKU'}).length,5);});
test('Westlake closed batch and CityU ordinary-date uncertainty are not promoted by other schools updates',()=>{for(const r of c.deadlines.filter(r=>r.institution==='Westlake'))assert.equal(deadlineStatus(r,c.metadata.checkedDate),'expired');assert.equal(d('cityu_me_rpg-main').date,'2026-12-01');assert.equal(route('cityu_me_rpg-phd').cycle2027Verified,true);assert.equal(d('cityu_me_rpg-main').cycleReview.history[0].sourceConflict.checkedDate,'2026-10-02');assert.equal(route('cityu_ds_mphil-excluded').defaultVisible,false);});
test('dated review does not falsify automated run success or historical normalized-source report',()=>{const status=read('update-status.json'),manifest=read('catalog-test-manifest.json');assert.equal(status.lastSuccessfulCheck,null);assert.equal(status.firstRunVerified,false);assert.equal(manifest.checkedDate,'2026-10-01');assert.equal(manifest.sha256,'094e513c0a2120bb2bee44efda475e2800537bcba797468add44bf5a479bd605');assert.equal(manifest.currentCycleReview.catalogSha256,'f3b9cf4e8bdf23167f94a897d9891c9c01b19ad27de051047cd9128d17e4177c');assert.equal(manifest.currentIdentityReview.catalogSha256,crypto.createHash('sha256').update(recruitmentBaselineText(c)).digest('hex'));});

test('dated PI recruitment maintenance preserves all historical sourceRecord snapshots exactly',()=>{assert.equal(hash(recruitmentBaseline(c).advisors.map(a=>a.sourceRecord??null)),'7e94314267698f5dffffaa0fabd219ea77f98fe5b7fada728d7ef5dac6ee8a9a');for(const id of ['hkust-yajing-shen','polyu_pai_zheng']){const a=c.advisors.find(a=>a.id===id);assert.equal(a.checkedDate,'2026-10-01');assert.equal(a.recruitmentReview.checkedDate,'2026-10-02');}});
