// Append future independently reviewed fact deltas here; never rewrite old receipts.
export const evidenceReviews=Object.freeze([{path:'tests/fixtures/evidence/maintenance-20261008.json',sha256:'d6fd6d89e68c82328f168301f2c7425c070645c3f8c1e9101101833268ed3f07'},{path:'tests/fixtures/evidence/homepages-20261010.json',sha256:'357e92c32d5d194eef4c0a953f2635f4e31749e3ec7dedf88b8734a8372be53a'},{path:'tests/fixtures/evidence/appointments-20261010.json',sha256:'49d0b3ced5962b4686c0e368998f471bc20a8922e5e4ce2155aab9156a8e99c3'},{path:'tests/fixtures/evidence/maintenance-20261009.json',sha256:'fe81a90659e8e80ef3378baab52f95226806179dcc22e5e27f59c810e01062d4'}]);

// Test-only exact inverses for three independent reviewed fact changes.
// Hashes and complete path lists are fixed; unknown facts cannot be stripped away.
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const boundedMaintenanceReviews=[
 {
  "path": "tests/fixtures/evidence/maintenance-20261009.json",
  "sha256": "fe81a90659e8e80ef3378baab52f95226806179dcc22e5e27f59c810e01062d4",
  "reviewDate": "2026-10-09",
  "operations": [
   [
    "data/catalog.json",
    "/advisors/9/opening",
    "replace"
   ],
   [
    "data/catalog.json",
    "/advisors/9/openingSummary",
    "replace"
   ],
   [
    "data/catalog.json",
    "/advisors/9/openings/phd",
    "replace"
   ],
   [
    "data/catalog.json",
    "/advisors/9/openings/cycle2027",
    "replace"
   ],
   [
    "data/catalog.json",
    "/advisors/9/openingDetails/2",
    "replace"
   ],
   [
    "data/catalog.json",
    "/advisors/9/recruitmentReview",
    "replace"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/11/recruitment",
    "replace"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/11/unknowns/0",
    "replace"
   ]
  ]
 },
 {
  "path": "tests/fixtures/evidence/appointments-20261010.json",
  "sha256": "49d0b3ced5962b4686c0e368998f471bc20a8922e5e4ce2155aab9156a8e99c3",
  "reviewDate": "2026-10-10",
  "operations": [
   [
    "data/advisor-profiles.json",
    "/profiles/0/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/1/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/2/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/3/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/4/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/5/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/6/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/7/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/8/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/9/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/10/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/11/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/12/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/13/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/14/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/15/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/16/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/17/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/18/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/19/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/20/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/21/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/22/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/23/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/24/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/25/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/26/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/27/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/28/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/29/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/30/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/31/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/32/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/33/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/34/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/35/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/36/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/37/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/38/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/39/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/40/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/41/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/42/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/43/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/44/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/45/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/46/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/47/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/48/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/49/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/50/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/51/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/52/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/53/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/54/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/55/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/56/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/57/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/58/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/59/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/60/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/61/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/62/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/63/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/64/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/65/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/66/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/67/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/68/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/69/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/70/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/71/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/72/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/73/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/74/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/75/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/76/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/77/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/78/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/79/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/80/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/81/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/82/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/83/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/84/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/85/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/86/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/87/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/88/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/89/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/90/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/91/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/92/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/93/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/94/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/95/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/96/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/97/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/98/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/99/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/100/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/101/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/102/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/103/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/104/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/105/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/106/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/107/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/108/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/109/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/110/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/111/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/112/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/113/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/114/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/115/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/116/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/117/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/118/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/119/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/120/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/121/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/122/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/123/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/124/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/125/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/126/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/127/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/128/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/129/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/130/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/131/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/132/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/133/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/134/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/135/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/136/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/137/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/138/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/139/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/140/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/141/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/142/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/143/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/144/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/145/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/146/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/147/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/148/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/149/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/150/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/151/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/152/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/153/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/154/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/155/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/156/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/157/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/158/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/159/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/160/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/161/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/162/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/163/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/164/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/165/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/166/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/167/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/168/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/169/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/170/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/171/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/172/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/173/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/174/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/175/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/176/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/177/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/178/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/179/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/180/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/181/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/182/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/183/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/184/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/185/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/186/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/187/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/188/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/189/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/190/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/191/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/192/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/193/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/194/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/195/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/196/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/197/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/198/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/199/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/200/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/201/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/202/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/203/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/204/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/205/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/206/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/207/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/208/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/209/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/210/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/211/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/212/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/213/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/214/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/215/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/216/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/217/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/218/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/219/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/220/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/221/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/222/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/223/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/224/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/225/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/226/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/227/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/228/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/229/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/230/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/231/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/232/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/233/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/234/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/235/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/236/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/237/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/238/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/239/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/240/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/241/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/242/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/243/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/244/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/245/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/246/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/247/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/248/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/249/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/250/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/251/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/252/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/253/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/254/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/255/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/256/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/257/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/258/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/259/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/260/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/261/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/262/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/263/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/264/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/265/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/266/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/267/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/268/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/269/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/270/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/271/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/272/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/273/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/274/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/275/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/276/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/277/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/278/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/279/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/280/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/281/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/282/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/283/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/284/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/285/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/286/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/287/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/288/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/289/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/290/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/291/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/292/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/293/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/294/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/295/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/296/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/297/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/298/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/299/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/300/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/301/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/302/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/303/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/304/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/305/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/306/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/307/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/308/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/309/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/310/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/311/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/312/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/313/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/314/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/315/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/316/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/317/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/318/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/319/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/320/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/321/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/322/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/323/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/324/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/325/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/326/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/327/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/328/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/329/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/330/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/331/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/332/appointmentReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/333/appointmentReview",
    "add"
   ]
  ]
 },
 {
  "path": "tests/fixtures/evidence/homepages-20261010.json",
  "sha256": "357e92c32d5d194eef4c0a953f2635f4e31749e3ec7dedf88b8734a8372be53a",
  "reviewDate": "2026-10-10",
  "operations": [
   [
    "data/advisor-profiles.json",
    "/profiles/41/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/41/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/42/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/42/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/43/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/43/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/44/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/44/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/45/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/45/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/51/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/51/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/55/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/55/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/63/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/63/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/64/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/64/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/72/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/72/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/73/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/73/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/88/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/88/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/89/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/89/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/110/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/110/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/130/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/130/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/131/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/131/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/132/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/132/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/136/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/136/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/137/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/137/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/139/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/139/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/143/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/143/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/180/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/180/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/181/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/181/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/182/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/182/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/183/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/183/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/185/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/185/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/186/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/186/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/187/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/187/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/189/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/189/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/190/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/190/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/191/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/191/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/193/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/193/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/194/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/194/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/195/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/195/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/198/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/198/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/234/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/234/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/237/links/3",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/237/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/239/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/239/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/240/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/240/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/242/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/242/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/244/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/244/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/245/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/245/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/246/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/246/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/247/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/247/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/249/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/249/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/258/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/258/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/306/links/4",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/306/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/307/links/4",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/307/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/308/links/4",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/308/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/310/links/4",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/310/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/331/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/331/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/332/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/332/links/2",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/332/homepageReview",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/333/links/1",
    "add"
   ],
   [
    "data/advisor-profiles.json",
    "/profiles/333/homepageReview",
    "add"
   ]
  ]
 }
];
export function reverseBoundedMaintenanceReviews(data,read){
 const restored=structuredClone(data);
 for(const spec of boundedMaintenanceReviews){
  const raw=read(spec.path);
  assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),spec.sha256,'unreviewed bounded receipt: '+spec.path);
  const review=JSON.parse(raw);
  assert.equal(review.schemaVersion,1);assert.equal(review.baseCommit,'4653bbd56a237a618a58c6f599e32e071ddf7094');assert.equal(review.reviewDate,spec.reviewDate);
  assert.deepEqual(review.operations.map(op=>[op.file,op.path,op.operation]),spec.operations,'exact bounded maintenance paths and operations');
  for(const op of [...review.operations].reverse()){
   const keys=op.path.slice(1).split('/');let owner=restored[op.file];assert(owner,'known bounded dataset');
   for(const key of keys.slice(0,-1)){assert(Object.hasOwn(owner,key),'existing bounded parent');owner=owner[key];}
   const key=keys.at(-1);assert(Object.hasOwn(owner,key),'existing bounded after-value');
   assert.deepEqual(owner[key],op.value,'exact reviewed after-value before historical inversion: '+op.path);
   if(op.operation==='replace')owner[key]=structuredClone(op.old);
   else{
    assert.equal(op.operation,'add');
    if(Array.isArray(owner)){assert.equal(Number(key),owner.length-1,'reverse only the exact appended tail');owner.pop();}
    else delete owner[key];
   }
  }
 }
 return restored;
}
