// Optional real-browser regression; does not claim acceptance when Chromium cannot launch.
import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const base=(process.env.TEST_URL||'http://127.0.0.1:4186').replace(/\/$/,'');const out=process.env.QA_OUTPUT||'/tmp/grad-reading-qa';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const checks=[];const errors=[];const check=(name,ok)=>{assert(ok,name);checks.push(name)};
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(String(e)));await page.goto(base);await page.waitForSelector('.advisor-card');
 await page.selectOption('#institution-filter','PolyU');await page.selectOption('#rank-filter','associate');await page.selectOption('#opportunity-filter','RA');await page.selectOption('#opening-filter','explicit');
 check('advisor choices select two RA opportunities',(await page.locator('#result-count').innerText())==='2 条机会 · 1 位导师');
 await page.click('nav [data-view="materials"]');check('material view starts independently with fourteen groups',(await page.locator('#result-count').innerText())==='14 组材料要求');
 for(const id of ['rank','topic','opening'])check('irrelevant material control hidden '+id,!(await page.locator('#'+id+'-filter-label').isVisible()));
 check('material degree label is relevant',(await page.locator('#opportunity-filter-name').innerText())==='适用学位');check('material RA option absent',await page.locator('#opportunity-filter option[value="RA"]').count()===0);
 await page.selectOption('#institution-filter','HKU');check('material school works',(await page.locator('#result-count').innerText())==='1 组材料要求');
 await page.click('nav [data-view="routes"]');check('project view ignores advisor and material filters',(await page.locator('#result-count').innerText())==='27 个学位项目');
 for(const id of ['rank','topic','opening'])check('irrelevant project control hidden '+id,!(await page.locator('#'+id+'-filter-label').isVisible()));
 await page.click('nav [data-view="deadlines"]');check('calendar school visible',await page.locator('#institution-filter-label').isVisible());
 for(const id of ['rank','topic','opening','opportunity'])check('irrelevant calendar control hidden '+id,!(await page.locator('#'+id+'-filter-label').isVisible()));check('calendar search hidden',!(await page.locator('.search-surface').isVisible()));
 await page.click('nav [data-view="materials"]');check('material school restored',(await page.locator('#institution-filter').inputValue())==='HKU');await page.click('#reset-filters');
 await page.click('nav [data-view="advisors"]');check('advisor selection restored',(await page.locator('#result-count').innerText())==='2 条机会 · 1 位导师'&&(await page.locator('#rank-filter').inputValue())==='associate'&&(await page.locator('#opportunity-filter').inputValue())==='RA'&&(await page.locator('#opening-filter').inputValue())==='explicit');
 await page.click('nav [data-view="experiences"]');await page.waitForSelector('.experience-card');check('four experience cards',await page.locator('.experience-card').count()===4);check('no advisor filters on experiences',!(await page.locator('.filters').isVisible())&&!(await page.locator('.search-surface').isVisible()));
 check('one action per card',await page.locator('.experience-card a').count()===4&&await page.locator('.experience-card button').count()===0);check('no direct original links in cards',await page.locator('.experience-card a[target="_blank"]').count()===0);check('one short introduction',await page.locator('.experience-intro').count()===1&&!(await page.locator('#view-description').isVisible()));
 check('case evidence links directly to reading',await page.locator('.experience-related a[href^="#experiences/"]').count()>0&&await page.locator('[data-experience-jump]').count()===0);
 await page.screenshot({path:out+'/desktop-list.png',fullPage:true});
 const firstHref=await page.locator('.experience-related a').first().getAttribute('href');await page.locator('.experience-related a').first().click();await page.waitForSelector('.experience-reading');check('overview opens full reading immediately',page.url().endsWith(firstHref)&&!(await page.locator('#detail-dialog').isVisible()));
 for(const text of ['这篇经验的总结','背景与申请目标','文中记录与结果','可借鉴的做法','适合怎么用','不能照搬的部分'])check('individual summary section '+text,(await page.locator('.experience-reading').innerText()).includes(text));
 check('only original link after reading',await page.locator('.experience-reading a[target="_blank"][rel="noopener noreferrer"]').count()===1);
 await page.goBack();await page.waitForSelector('.experience-card');check('Back returns to experience list',await page.locator('.experience-card').count()===4);await page.goForward();await page.waitForSelector('.experience-reading');check('Forward restores reading',page.url().endsWith(firstHref));const direct=await browser.newPage();direct.on('pageerror',e=>errors.push(String(e)));await direct.goto(base+'/'+firstHref);await direct.waitForSelector('.experience-reading');await direct.reload();await direct.waitForSelector('.experience-reading');check('direct refresh preserves reading route',direct.url().endsWith(firstHref));await direct.close();
 await page.locator('.experience-back').click();await page.waitForSelector('.experience-card');await page.locator('.experience-card .experience-read-link').first().focus();await page.keyboard.press('Enter');await page.waitForSelector('.experience-reading');check('keyboard CTA opens reading',await page.locator('.experience-reading').isVisible());
 await page.locator('.experience-reading summary').focus();await page.keyboard.press('Enter');check('keyboard exposes evidence',await page.locator('.experience-reading details').getAttribute('open')!==null);await page.screenshot({path:out+'/desktop-reading.png',fullPage:true});
 await page.locator('.experience-back').click();await page.click('nav [data-view="advisors"]');check('advisor choices survive reading round trip',(await page.locator('#result-count').innerText())==='2 条机会 · 1 位导师');await page.click('#reset-filters');check('advisor totals remain unchanged',(await page.locator('#result-count').innerText())==='46 条机会 · 30 位导师');
 for(const width of [390,320]){
  await page.setViewportSize({width,height:844});await page.goto(base+'/#experiences');await page.waitForSelector('.experience-card');check('mobile navigation fits '+width,await page.locator('nav').evaluate(n=>n.scrollWidth<=n.clientWidth));check('mobile list no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:out+'/mobile-list-'+width+'.png',fullPage:true});await page.locator('[data-experience-id="grad-europe-tinsir-2025"] .experience-read-link').click();await page.waitForSelector('.experience-reading');check('mobile master boundary preserved '+width,(await page.locator('.experience-reading').innerText()).includes('不证明本科直博资格'));check('mobile reading no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:out+'/mobile-reading-'+width+'.png',fullPage:true});await page.locator('.experience-back').click();await page.waitForSelector('.experience-card');check('mobile clear return works '+width,await page.locator('.experience-card').count()===4);
 }
 await page.goto(base+'/#experiences/missing');await page.getByRole('heading',{name:'未找到这篇经验'}).waitFor();check('invalid reading URL has usable return',await page.locator('.experience-back').isVisible());
 const failed=await browser.newPage();failed.on('pageerror',e=>errors.push(String(e)));await failed.route('**/data/application-experiences.json',r=>r.fulfill({status:503,body:''}));await failed.route('**/data/material-summaries.json',r=>r.fulfill({status:503,body:''}));await failed.goto(base+'/#experiences/grad-europe-tinsir-2025');await failed.getByRole('heading',{name:'经验资料暂时无法读取'}).waitFor();check('reading load failure honest',await failed.locator('.experience-back').isVisible());await failed.click('nav [data-view="materials"]');check('material fallback preserved',await failed.locator('#view-content .route-card').count()===2&&(await failed.locator('#view-content').innerText()).includes('补充材料资料暂未载入'));await failed.click('nav [data-view="advisors"]');await failed.waitForSelector('.advisor-card');check('optional failures do not break advisors',await failed.locator('.advisor-card').count()===46);check('no runtime errors',errors.length===0);
 fs.writeFileSync(out+'/report.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors,out}));
}finally{await browser.close()}
