import test from 'node:test';import assert from 'node:assert/strict';import fs from './public-audit-20261006-history-fs.mjs';import crypto from 'node:crypto';
import {normalizeExperiences,renderExperiences as renderExperienceList,renderExperienceEvidence,renderExperienceReading} from '../assets/experiences.js';
function renderExperiences(records){const result=renderExperienceList(records);return {...result,html:renderExperienceEvidence(records)+result.html};}

import {buildPageOverview} from '../assets/page-overviews.js';
const read=name=>JSON.parse(fs.readFileSync(new URL('../data/'+name,import.meta.url)));
const raw=read('application-experiences.json'),records=normalizeExperiences(raw),added=records.slice(16,19),provenance=read('application-experience-provenance.json');
const ids=['grad-sustech-lisr-hkust-2025','grad-ruakoyo-hku-interview-2024','grad-shufly-w-hongkong-2024'];
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
test('three independently reviewed additions preserve all sixteen published objects exactly',()=>{assert.equal(records.length,26);assert.equal(raw.records.length,26);assert.deepEqual(added.map(r=>r.id),ids);assert.equal(digest(records.slice(0,16)),'8ca2052a8244dbf1567986803749e02a113f4698d10d6643074133bcb86b5259');assert.equal(provenance.records.length,26);});
test('HKUST oral support and subsequent US PhD decisions remain separate across cycles',()=>{const r=added[0];assert.equal(r.publishedAt,null);assert(r.applicableCycle.includes('2023 年秋'));for(const s of ['口头支持','未得到正式 offer','25Fall','UCLA'])assert(r.outcome.includes(s));assert(r.dateNote.includes('上传不等同原始发表日'));assert(r.excludedClaims.join('').includes('不据此计算'));assert(r.commercialDisclosure.includes('中介'));});
test('HKU failure retains causal uncertainty and no invented final outcome',()=>{const r=added[1];assert.equal(r.publishedAt,'2024-08-10');assert(r.outcome.includes('没有最终学位录取结果'));assert(r.summary.includes('不能认定网络故障就是拒绝原因'));assert(r.dateNote.includes('没有具体面试日'));assert(r.commercialDisclosure.includes('商业留学服务'));});
test('SHUFly separates admissions, shortlist, invitations and applicant withdrawal',()=>{const r=added[2];assert.equal(r.publishedAt,'2024-04-02');for(const s of ['接受 CUHK CS','HKUST IT 录取后放弃','CUHK IE/EE 到 shortlist','HKU CS 到面试邀请','不能将这些未继续的项目写成学校拒绝'])assert(r.outcome.includes(s));assert(r.dateNote.includes('2026-09-05'));assert(r.dateNote.includes('不是新的申请季'));assert(r.applicableCycle.includes('2023 年秋'));});
test('all twenty-six records are substantively cited before the card list and every new reading retains sources',()=>{const overview=renderExperienceEvidence(records);assert(overview.includes('这 26 篇经验的逐项依据'));assert(!overview.includes('尚未纳入'));for(const r of records)assert(overview.includes('#experiences/'+r.id),r.id);for(const r of added){const h=renderExperienceReading(records,r.id).html;assert(h.includes(r.dateNote));assert(h.includes(r.commercialDisclosure));assert(h.includes(`href="${r.url}"`));assert(h.indexOf('不能照搬的部分')<h.indexOf('查看原帖'));const p=provenance.records.find(p=>p.id===r.id);assert(p.independentReview.mode.includes('reread'));assert(p.fieldLocations.summary&&p.fieldLocations.outcome);}});
test('page-wide overview requires the full reviewed twenty-six-case scope and exposes the recent evidence',()=>{const catalog=read('catalog.json');const full=JSON.stringify(buildPageOverview('experiences',catalog,{experiences:records}));for(const s of ['26 篇公开自述','SHUFly','lisr20','港大工程失利','HKUST 口头支持','机器人 MPhil'])assert(full.includes(s));for(const r of records){const partial=JSON.stringify(buildPageOverview('experiences',catalog,{experiences:records.filter(x=>x.id!==r.id)}));assert(partial.includes('部分归纳依据暂未载入'),r.id);assert(!partial.includes('experience-synthesis'));}});
test('unreviewed future additions do not silently enter a whole-collection conclusion',()=>{const extra={...records[0],id:'pending-source',url:'https://example.org/pending-source'};const h=renderExperiences([...records,extra]).html;assert(h.includes('这 26 篇经验'));assert(h.includes('另有 1 篇新收录经验尚未纳入'));assert(!h.includes('这 27 篇经验'));const p=buildPageOverview('experiences',read('catalog.json'),{experiences:[...records,extra]});assert.equal(p.scope,'已归纳 26 篇公开自述 · 另 1 篇待综合');});
test('public additions contain only scoped public process summaries',()=>{const text=JSON.stringify({records:added,provenance:provenance.records.slice(16,19)});for(const s of ['xsec_token','xsec_source','/workspace/','rawHtml','mailto:','tel:'])assert(!text.includes(s),s);assert(!/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i.test(text));for(const r of added){assert.equal(new URL(r.url).search,'');assert.equal(r.checkedAt,'2026-10-02');assert.equal(r.rulesImpact,'none');assert.equal(r.evidenceType,'first_person_self_report');assert(!Object.hasOwn(r,'eligibility'));assert(!Object.hasOwn(r,'advisorId'));if(r.publishedAt)assert(r.publishedAt<=r.checkedAt);}});
