import test from 'node:test';import assert from 'node:assert/strict';
// Synthetic fixtures only: no public profile records or personal contact data.
class Element{constructor(){this.value='';this.hidden=false;this.innerHTML='';this.textContent='';this.listeners={};this.attrs={};this.classList={toggle(){}};}addEventListener(k,f){this.listeners[k]=f}setAttribute(k,v){this.attrs[k]=v}removeAttribute(k){delete this.attrs[k]}focus(){document.activeElement=this}}
const nodes=new Map();const el=s=>{if(!nodes.has(s))nodes.set(s,new Element());return nodes.get(s)};const events={};const navigation={};
globalThis.document={querySelector:el,querySelectorAll:()=>[],addEventListener:(k,f)=>events[k]=f,activeElement:{tagName:'BODY'}};globalThis.window={addEventListener:(k,f)=>navigation[k]=f};globalThis.location={hash:''};
const record={id:'sample-bachelor',title:'Synthetic preparation example',url:'https://example.org/bachelor',platform:'Sample source',author:'Example author',applicableCycle:'2020 historical cycle',background:'Bachelor',authorContext:'Synthetic background',outcome:'Self-reported outcome',summary:'Preparation example',readScope:'Main text only',dateNote:'Publication unknown',bachelorApplicability:'Methods only',commercialDisclosure:'Not assessed',checkedAt:'2026-10-01',evidenceType:'first_person_self_report',rulesImpact:'none',collection:'bachelor',actionableMethods:['Plan ahead'],excludedClaims:['Success guarantees']};
globalThis.fetch=async url=>({ok:true,json:async()=>String(url).endsWith('application-experiences.json')?{schemaVersion:1,records:[record,{...record,id:'sample-master',url:'https://example.org/master',collection:'cross-background'}]}:String(url).endsWith('update-status.json')?{statusLabel:'Test fixture'}:{metadata:{checkedDate:'2026-10-01'},advisors:[],routes:[],raPositions:[],profiles:[]}});
await import('../assets/app.js');await new Promise(r=>setImmediate(r));const view=name=>{location.hash='#'+name;navigation.hashchange()};
test('experience navigation is independent, preserves filters, and restores keyboard focus',()=>{el('#rank-filter').value='associate';el('#rank-filter').listeners.change({target:el('#rank-filter')});view('experiences');assert(el('.filters').hidden);assert(el('.search-surface').hidden);assert(el('#view-content').innerHTML.includes('sample-bachelor'));assert(!el('#view-content').innerHTML.includes('sample-master'));events.click({target:{closest:s=>s==='[data-experience-scope]'?{dataset:{experienceScope:'cross-background'}}:null}});assert(el('#view-content').innerHTML.includes('sample-master'));assert(!el('#view-content').innerHTML.includes('sample-bachelor'));assert.equal(document.activeElement,el('[data-experience-scope][aria-pressed="true"]'));view('advisors');assert(!el('.filters').hidden);assert.equal(el('#rank-filter').value,'associate');assert.equal(el('#result-count').textContent,'0 条机会 · 0 位导师');});
