import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {normalizeExperiences,renderExperiences as renderExperienceList,renderExperienceEvidence,renderExperienceReading} from '../assets/experiences.js';
function renderExperiences(records){const result=renderExperienceList(records);return {...result,html:renderExperienceEvidence(records)+result.html};}

const raw=JSON.parse(fs.readFileSync(new URL('../data/application-experiences.json',import.meta.url)));const records=normalizeExperiences(raw);const get=id=>records.find(r=>r.id===id);const tail=records.slice(11,16);
test('second batch preserves every published eleven-case object exactly',()=>{assert.equal(crypto.createHash('sha256').update(JSON.stringify(records.slice(0,11))).digest('hex'),'e3db97539299591bdea637209404d9b1aeeed9cd34f1f74185818e427d7e7308');assert.equal(tail.length,5);assert.equal(records.length,21);});
test('CUHK cross-cycle author update is distinct from unverified RA employment',()=>{const r=get('grad-gter-chuyeyue-ra-phd-2024');assert(r.outcome.includes('2024-06-13'));assert(r.outcome.includes('RA 实际入职'));assert(r.outcome.includes('未说明'));assert(r.summary.includes('不能补写'));assert(r.commercialDisclosure.includes('销售'));assert(r.excludedClaims.join('').includes('不是香港 MPhil'));assert(r.readScope.includes('同一作者账号'));});
test('2018 and 2015 MPhil cases retain historical dates, status and incomplete background',()=>{const a=get('grad-gter-sscomebady-mphil-2018');assert(a.title.includes('历史'));assert(a.authorContext.includes('一篇一作在投'));assert(a.authorContext.includes('两篇非一作已接受'));assert(a.outcome.includes('推研'));assert(a.outcome.includes('正式 offer'));assert(a.commercialDisclosure.includes('知乎 Live'));const b=get('grad-gter-imhigh-hkust-mphil-2015');assert.equal(b.publishedAt,null);assert(b.dateNote.includes('2014—2015'));assert(b.excludedClaims.join('').includes('1970'));assert(b.excludedClaims.join('').includes('2020'));assert(b.outcome.includes('邀请不计作 PhD 录取'));assert(b.authorContext.includes('留空'));});
test('summer internship is never an employed RA or accepted paper',()=>{const r=get('grad-drishti-akash-hkust-intern-2023');assert(r.title.includes('相关经历'));assert(r.applicableCycle.includes('不是全职 RA'));assert(r.outcome.includes('不是论文录用'));assert(r.outcome.includes('UPC RA 只是未来计划'));assert(r.readScope.includes('评论需另行加载，未读'));});
test('cryptography account discloses mixed offer statuses, update date and same-cycle scope',()=>{const r=get('grad-wangbard-cryptography-phd-2025');assert(r.title.includes('相关经历'));assert(r.dateNote.includes('2025-09-18'));assert(r.outcome.includes('稳定口头'));assert(r.excludedClaims.join('').includes('不标为跨年重申'));assert(r.excludedClaims.join('').includes('没有香港 MPhil'));assert(r.authorContext.includes('没有 GPA'));});
test('five additions are present in synthesis and every reading preserves boundaries',()=>{const h=renderExperienceEvidence(records);assert(h.includes('这 21 篇经验'));for(const r of tail){assert(h.includes('#experiences/'+r.id));const html=renderExperienceReading(records,r.id).html;assert(html.includes(r.commercialDisclosure));assert(html.includes(r.dateNote));assert(html.indexOf('不能照搬的部分')<html.indexOf('查看原帖'));}assert(h.includes('全职 RA'));assert(h.includes('跨申请季'));assert(h.includes('历史样本'));});
test('new public summaries omit exact grades, contacts, signed links and raw-source payloads',()=>{const text=JSON.stringify(tail);for(const term of ['xsec_token','rawHtml','/workspace/','海王'])assert(!text.includes(term));assert(!/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i.test(text));const prose=JSON.stringify(tail.map(({url,id,...record})=>record));assert(!/\b\d{7,}\b/.test(prose));assert(!/\b\d{2}\.\d\b/.test(prose));assert(!/\b\d{2}-\d{2}\b/.test(prose.replace(/\d{4}-\d{2}-\d{2}/g,'')));for(const r of tail){assert.equal(new URL(r.url).search,'');assert.equal(r.checkedAt,'2026-10-02');}});
