import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {normalizeExperiences,filterExperiences,renderExperiences} from '../assets/experiences.js';
const raw=JSON.parse(fs.readFileSync(new URL('../data/application-experiences.json',import.meta.url)));const records=normalizeExperiences(raw);
test('qualified experience sources are separate from recruitment data',()=>{assert.equal(records.length,4);assert.equal(new Set(records.map(r=>r.url)).size,4);for(const r of records){assert.equal(r.rulesImpact,'none');assert.equal(r.evidenceType,'first_person_self_report');assert(!Object.hasOwn(r,'advisorId'));assert(!Object.hasOwn(r,'eligibility'));}});
test('default shows only bachelor history; cross-background requires explicit scope',()=>{assert.equal(filterExperiences(records).length,3);assert.equal(filterExperiences(records)[0].id,'grad-robotics-eth-xiang-2022');assert.equal(filterExperiences(records,'cross-background')[0].id,'grad-europe-tinsir-2025');assert.equal(filterExperiences(records,'all').length,3);});
test('missing, duplicate and unsafe sources fail closed',()=>{const r=records[0];for(const url of [null,'','javascript:alert(1)','http://example.com'])assert.equal(normalizeExperiences({schemaVersion:1,records:[{...r,url}]}).length,0);assert.equal(normalizeExperiences({schemaVersion:1,records:[r,r]}).length,1);assert.throws(()=>normalizeExperiences({records}));assert.equal(normalizeExperiences({schemaVersion:1,records:[{...r,readScope:''}]}).length,0);});
test('card escapes content and distinguishes historical claims and evidence scope',()=>{const h=renderExperiences([{...records[0],title:'<img onerror="bad">'}]).html;assert(h.includes('&lt;img'));assert(!h.includes('<img'));for(const text of ['不计入导师与机会数量','历史亲历','结果自报','核读范围','未采纳为事实或建议','rel="noopener noreferrer"','对本科申请的适用范围'])assert(h.includes(text));});
test('unavailable and empty experience data have distinct honest states',()=>{assert(renderExperiences(null).html.includes('经验资料暂时无法读取'));assert(renderExperiences([]).html.includes('暂无符合来源要求'));assert(!renderExperiences(null).html.includes('data-experience-id='));});
test('published date is not invented from cohort or application year',()=>{const r=records.find(r=>r.collection==='bachelor');assert.equal(r.publishedAt,null);assert(r.dateNote.includes('18是年级标签'));assert(r.applicableCycle.includes('2022'));});
test('experience public payload excludes unavailable XHS permalink and private identifiers',()=>{const text=JSON.stringify(raw);for(const forbidden of ['xhs-polyu','xiaohongshu','xsec_token','entryUrl','@gmail.com','微信','申请编号','/workspace/'])assert(!text.includes(forbidden));});
