// Optional local browser regression; test-only dependency, not shipped to browsers.
import {createRequire} from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:4186';
const out=process.env.QA_OUTPUT||'/tmp/grad-experience-qa';
fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const checks=[];
const errors=[];
const check=(name,ok)=>{assert(ok,name);checks.push(name)};
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(base);
 await page.waitForSelector('.advisor-card');
 await page.selectOption('#rank-filter','associate');
 await page.click('[data-view="experiences"]');
 await page.waitForSelector('.experience-card');
 check('main navigation uses five clear names',JSON.stringify(await page.locator('nav [data-view] > span').allInnerTexts())===JSON.stringify(['找导师','找项目','申请日历','准备材料','申请经验']));
 check('data explanation moved to footer',await page.locator('header [data-view="sources"]').count()===0&&await page.locator('footer [data-view="sources"]').count()===1);
 check('experience purpose visible',await page.locator('#view-description').isVisible()&&(await page.locator('#view-description').innerText()).includes('结合作者背景'));
 check('all four experiences shown by default',await page.locator('.experience-card').count()===4);
 check('plain experience title and count',(await page.locator('#results-title').innerText())==='申请经验'&&(await page.locator('#result-count').innerText())==='4 条申请经验');
 check('artificial category controls removed',await page.locator('[data-experience-scope]').count()===0&&!(await page.locator('#view-content').innerText()).includes('本科申请方法'));
 check('global advisor filters hidden',!(await page.locator('.filters').isVisible())&&!(await page.locator('.search-surface').isVisible()));
 check('all cards label author background',await page.locator('.experience-background').count()===4&&(await page.locator('.experience-background').allInnerTexts()).every(t=>t.startsWith('作者背景：')));
 check('all cards label applicability',await page.locator('.experience-card .caution-box strong').count()===4&&(await page.locator('.experience-card .caution-box strong').allInnerTexts()).every(t=>t==='参考范围'));
 const master=page.locator('[data-experience-id="grad-europe-tinsir-2025"]');
 check('master-to-PhD boundary remains explicit',(await master.innerText()).includes('授课型硕士 → PhD')&&(await master.innerText()).includes('不证明本科直博资格'));
 check('overview comes before articles',await page.locator('.experience-overview').isVisible());
 check('experience list has no outgoing original-post links',await page.locator('.experience-card a[target="_blank"]').count()===0);
 await page.locator('.experience-card [data-experience-summary]').first().focus();
 await page.keyboard.press('Enter');
 await page.waitForSelector('#detail-dialog[open]');
 check('keyboard opens in-site experience summary',(await page.locator('#detail-kind').innerText())==='申请经验摘要');
 check('summary retains process and outcome',(await page.locator('#detail-content').innerText()).includes('申请过程与结果'));
 check('original post is offered after summary',await page.locator('#detail-content a[target="_blank"][rel="noopener noreferrer"]').count()===1);
 await page.locator('#detail-content summary').focus();
 await page.keyboard.press('Enter');
 check('keyboard expands evidence',await page.locator('#detail-content details').getAttribute('open')!==null);
 await page.keyboard.press('Escape');
 check('Escape closes summary',!(await page.locator('#detail-dialog').isVisible()));
 await page.screenshot({path:out+'/desktop.png',fullPage:true});
 await page.click('[data-view="experiences"]');
 check('repeat experience navigation stable',await page.locator('.experience-card').count()===4);
 await page.click('[data-view="advisors"]');
 check('rank preserved',(await page.locator('#result-count').innerText())==='15 条机会 · 9 位导师');
 await page.goBack();
 await page.waitForSelector('.experience-card');
 check('back restores all experiences',await page.locator('.experience-card').count()===4);
 await page.goForward();
 await page.waitForSelector('.advisor-card');
 check('forward restores advisor filters',(await page.locator('#result-count').innerText())==='15 条机会 · 9 位导师');
 await page.click('#reset-filters');
 check('original counts intact',(await page.locator('#result-count').innerText())==='46 条机会 · 30 位导师');
 check('opportunity and person counts explained',(await page.locator('#view-description').innerText()).includes('同一导师可能有多条机会'));
 for(const [id,title,purpose] of [['routes','找项目','MSc、MPhil、PhD'],['deadlines','申请日历','未来截止日期不代表现在已开放申请'],['materials','准备材料','当期申请系统的完整清单']]){
  await page.click(`[data-view="${id}"]`);
  check('matching page title '+id,(await page.locator('#results-title').innerText())===title);
  check('visible accurate purpose '+id,(await page.locator('#view-description').innerText()).includes(purpose));
  check('list has no direct external links '+id,await page.locator('#view-content a[target="_blank"]').count()===0);
  const before=page.url();
  await page.locator('#view-content [data-summary-kind]').first().click();
  await page.waitForSelector('#detail-dialog[open]');
  check('in-site summary opens without navigation '+id,page.url()===before);
  check('official source links offered within summary '+id,await page.locator('#detail-content a[target="_blank"]').count()>0);
  await page.keyboard.press('Escape');
  check('summary closes without changing page '+id,page.url()===before&&!(await page.locator('#detail-dialog').isVisible()));
 }
 await page.click('footer [data-view="sources"]');
 check('footer source link works',(await page.locator('#results-title').innerText())==='数据说明与更新状态');
 for(const width of [390,320]){
  await page.setViewportSize({width,height:844});
  await page.goto(base+'/#experiences');
  await page.waitForSelector('.experience-card');
  check('mobile all five navigation items fit '+width,await page.locator('nav').evaluate(nav=>nav.scrollWidth<=nav.clientWidth));
  check('mobile purpose visible '+width,await page.locator('#view-description').isVisible());
  check('mobile all experiences visible '+width,await page.locator('.experience-card').count()===4);
  await master.locator('[data-experience-summary]').first().click();
  await page.locator('#detail-content summary').click();
  check('mobile expanded evidence readable '+width,await page.locator('#detail-content .experience-evidence').isVisible());
  check('mobile summary no horizontal overflow '+width,await page.locator('#detail-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1));
  await page.screenshot({path:out+'/mobile-summary-'+width+'.png',fullPage:true});
  await page.keyboard.press('Escape');
  check('mobile no horizontal overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:out+'/mobile-'+width+'.png',fullPage:true});
 }
 const failed=await browser.newPage();
 failed.on('pageerror',e=>errors.push(String(e)));
 await failed.route('**/data/application-experiences.json',r=>r.fulfill({status:503,body:''}));
 await failed.route('**/data/material-summaries.json',r=>r.fulfill({status:503,body:''}));
 await failed.goto(base+'/#experiences');
 await failed.getByText('经验资料暂时无法读取').waitFor();
 check('experience fetch failure isolated',true);
 await failed.click('[data-view="advisors"]');
 await failed.waitForSelector('.advisor-card');
 check('advisors survive optional data failure',await failed.locator('.advisor-card').count()===46);
 await failed.click('[data-view="materials"]');
 check('material load failure keeps original records',await failed.locator('#view-content .route-card').count()===2);
 check('material load failure disclosed',(await failed.locator('#view-content').innerText()).includes('补充材料资料暂未载入'));
 check('failed material load does not claim complete coverage',!(await failed.locator('#view-content').innerText()).includes('完整覆盖'));
 check('no runtime errors',errors.length===0);
 fs.writeFileSync(out+'/report.json',JSON.stringify({checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors,out}));
}finally{await browser.close()}
