import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {normalizeExperiences,renderExperiences,renderExperienceReading,experienceHref,applicabilityText} from '../assets/experiences.js';
const raw=JSON.parse(fs.readFileSync(new URL('../data/application-experiences.json',import.meta.url)));const records=normalizeExperiences(raw);
test('qualified experience sources remain separate from recruitment data',()=>{assert.equal(records.length,11);assert.equal(new Set(records.map(r=>r.url)).size,11);for(const r of records){assert.equal(r.rulesImpact,'none');assert.equal(r.evidenceType,'first_person_self_report');assert(!Object.hasOwn(r,'advisorId'));assert(!Object.hasOwn(r,'eligibility'));}});
test('experience list shows all records with exactly one reading action per card',()=>{const result=renderExperiences(records);assert.equal(result.countLabel,'11 条申请经验');assert.equal((result.html.match(/class="experience-card"/g)||[]).length,11);for(const r of records){const card=result.html.split(`data-experience-id="${r.id}"`)[1].split('</article>')[0];assert.equal((card.match(/<a /g)||[]).length,1);assert(card.includes(`href="${experienceHref(r.id)}"`));assert(card.includes('阅读经验'));assert(!card.includes('<button'));assert(card.indexOf('experience-takeaway')<card.indexOf('experience-background'));assert(!card.includes('caution-box'));}for(const removed of ['data-experience-summary','data-experience-jump','data-experience-scope','experience-tabs'])assert(!result.html.includes(removed));});
test('reading page preserves every source boundary and moves original post after full summary',()=>{for(const r of records){const result=renderExperienceReading(records,r.id);assert.equal(result.title,r.title);const h=result.html;for(const text of [r.authorContext,r.summary,r.outcome,applicabilityText(r),r.dateNote,r.readScope,r.commercialDisclosure,...r.actionableMethods,...r.excludedClaims]){const escaped=text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');assert(h.includes(escaped));}for(const section of ['这篇经验的总结','背景与申请目标','文中记录与结果','可借鉴的做法','适合怎么用','不能照搬的部分'])assert(h.includes(section));assert(h.indexOf('不能照搬的部分')<h.indexOf('查看原帖'));assert(h.includes('href="#experiences"'));assert(h.includes('rel="noopener noreferrer"'));}});
test('master-to-PhD reading never claims bachelor eligibility',()=>{const r=records.find(r=>r.collection==='cross-background');const h=renderExperienceReading(records,r.id).html;assert(h.includes('授课型硕士'));assert(h.includes('不证明本科直博资格'));assert(!h.includes('本科路径已核实'));assert(!h.includes('本科任职条件已核实'));});
test('synthesis maps the eleven cases directly to reading routes and explains differences',()=>{const h=renderExperiences(records).html;assert(h.includes('11 篇经验的综合总结'));assert(h.includes('准备顺序'));assert(h.includes('背景不同，参考重点也不同'));assert(h.includes('硕士毕业后返校做 RA'));assert(h.includes('本科阶段联系课题组'));assert(h.includes('不同项目也可能给出不同结果'));assert(h.includes('不同背景的结果不宜直接比较'));for(const r of records)assert(h.includes(`href="${experienceHref(r.id)}"`));assert(!h.includes('的经历</button>'));assert(h.indexOf('experience-overview')<h.indexOf('experience-grid'));assert(renderExperiences(records.slice(0,2)).html.includes('综合总结暂不完整'));});
test('unavailable data and invalid links have distinct honest reading states',()=>{assert(renderExperienceReading(null,records[0].id).html.includes('尚未载入'));assert(renderExperienceReading(records,'missing').html.includes('链接对应的经验不存在'));assert(renderExperiences([]).html.includes('暂无符合来源要求'));assert(!renderExperiences(null).html.includes('data-experience-id='));});
test('reading routes encode identifiers and all source text remains escaped',()=>{assert.equal(experienceHref('a b/c'),'#experiences/a%20b%2Fc');const malicious={...records[0],title:'<img onerror="bad">',summary:'<script>bad</script>'};const preview=renderExperiences([malicious]).html;const reading=renderExperienceReading([malicious],malicious.id).html;assert(preview.includes('&lt;img'));assert(reading.includes('&lt;script'));assert(!preview.includes('<img'));assert(!reading.includes('<script>'));assert(!preview.includes('target="_blank"'));});
test('missing, duplicate and unsafe experience sources fail closed',()=>{const r=records[0];for(const url of [null,'','javascript:alert(1)','http://example.com'])assert.equal(normalizeExperiences({schemaVersion:1,records:[{...r,url}]}).length,0);assert.equal(normalizeExperiences({schemaVersion:1,records:[r,r]}).length,1);assert.throws(()=>normalizeExperiences({records}));assert.equal(normalizeExperiences({schemaVersion:1,records:[{...r,readScope:''}]}).length,0);});
test('awkward categories and repeated overview disclaimers are absent',()=>{const h=renderExperiences(records).html+records.map(r=>renderExperienceReading(records,r.id).html).join('');for(const term of ['本科申请方法','跨背景流程对照','跨背景对照流程'])assert(!h.includes(term));assert.equal((renderExperiences(records).html.match(/class="experience-intro"/g)||[]).length,1);});
test('published dates and private-source boundaries remain unchanged',()=>{const r=records.find(r=>r.collection==='bachelor');assert.equal(r.publishedAt,null);assert(r.dateNote.includes('18是年级标签'));assert(r.applicableCycle.includes('2022'));const text=JSON.stringify(raw);for(const forbidden of ['xhs-polyu','xsec_token','entryUrl','@gmail.com','微信','申请编号','/workspace/'])assert(!text.includes(forbidden));});

test('a twelfth experience keeps the eleven-case synthesis and discloses its exact pending scope',()=>{const extra={...records[0],id:'new-case',title:'New case',url:'https://example.org/new-case'};const h=renderExperiences([...records,extra]).html;assert(h.includes('这 11 篇经验的综合总结'));assert(h.includes('另有 1 篇新收录经验尚未纳入本节归纳'));assert(!h.includes('这 12 篇经验的综合总结'));assert.equal((h.match(/class="experience-card"/g)||[]).length,12);assert(h.includes('href="#experiences/new-case"'));});
