import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
// Read shipped fixtures locally; assertions expose only aggregate counts and labels.
class Element{constructor(){this.value='';this.hidden=false;this.innerHTML='';this.textContent='';this.listeners={};this.attrs={};this.open=false;this.classList={toggle(){}};}addEventListener(k,f){this.listeners[k]=f}setAttribute(k,v){this.attrs[k]=v}removeAttribute(k){delete this.attrs[k]}focus(){document.activeElement=this}showModal(){this.open=true}close(){this.open=false}}
const nodes=new Map();const el=s=>{if(!nodes.has(s))nodes.set(s,new Element());return nodes.get(s)};const events={};const navigation={};
globalThis.document={querySelector:el,querySelectorAll:()=>[],getElementById:id=>el('#'+id),addEventListener:(k,f)=>events[k]=f,activeElement:{tagName:'BODY'}};globalThis.window={addEventListener:(k,f)=>navigation[k]=f};globalThis.location={hash:''};
globalThis.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(url,'utf8'))});
await import('../assets/app.js');await new Promise(r=>setImmediate(r));const view=name=>{location.hash='#'+name;navigation.hashchange()};
const change=(name,value)=>{el('#'+name+'-filter').value=value;el('#'+name+'-filter').listeners.change({target:el('#'+name+'-filter')})};
test('real app loads fourteen material groups while preserving opportunity and experience counts',()=>{assert.equal(el('#result-count').textContent,'46 条机会 · 30 位导师');view('materials');assert.equal(el('#result-count').textContent,'14 组材料要求');assert.equal((el('#view-content').innerHTML.match(/class="route-card"/g)||[]).length,14);assert(!el('#view-content').innerHTML.includes('补充材料资料暂未载入'));assert(!el('#view-content').innerHTML.includes('仅覆盖西湖'));assert(!el('#view-content').innerHTML.includes('target="_blank"'));view('experiences');assert.equal(el('#result-count').textContent,'4 条申请经验');});
test('material filters keep campus and degree scopes separate and never invent RA materials',()=>{view('materials');change('institution','HKUST(GZ)');assert.equal(el('#result-count').textContent,'2 组材料要求');change('opportunity','PhD');assert.equal(el('#result-count').textContent,'1 组材料要求');assert(el('#view-content').innerHTML.includes('hkust-gz-phd-materials'));assert(!el('#view-content').innerHTML.includes('hkust-gz-rbm-materials'));el('#reset-filters').listeners.click();change('opportunity','RA');assert.equal(el('#result-count').textContent,'0 组材料要求');assert(el('#view-content').innerHTML.includes('RA 岗位材料清单尚待核对'));assert(el('#view-content').innerHTML.includes('data-switch="advisors"'));assert(!el('#view-content').innerHTML.includes('class="route-card"'));el('#reset-filters').listeners.click();assert.equal(el('#result-count').textContent,'14 组材料要求');});
