import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeMaterialSupplement} from '../assets/material-supplement.js';
import {renderRecordSummary} from '../assets/record-summaries.js';
import {isVerifiedRoute,buildOpportunities} from '../assets/core.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url)));const raw=JSON.parse(fs.readFileSync(new URL('../data/material-summaries.json',import.meta.url)));const records=normalizeMaterialSupplement(raw,catalog);
test('twelve official material groups extend two preserved Westlake records to fourteen',()=>{assert.equal(records.length,12);assert.equal(catalog.materials.length,2);assert(catalog.materials.every(m=>m.institution==='Westlake'));assert.equal(new Set([...catalog.materials,...records].map(r=>r.id)).size,14);assert.equal(raw.sources.length,33);const routes=new Set(records.flatMap(r=>r.routeIds));assert.equal(routes.size,25);for(const route of catalog.routes.filter(r=>isVerifiedRoute(r)&&r.institution!=='Westlake'))assert(routes.has(route.id));});
test('material supplements do not change admissions, advisors, or RA eligibility',()=>{const before=JSON.stringify(catalog);normalizeMaterialSupplement(raw,catalog);assert.equal(JSON.stringify(catalog),before);const ra=JSON.parse(fs.readFileSync(new URL('../data/ra-positions.json',import.meta.url))).raPositions;const merged={...catalog,raPositions:ra,materials:[...catalog.materials,...records]};assert.equal(buildOpportunities(merged).length,46);assert.equal(new Set(buildOpportunities(merged).map(o=>o.advisorId)).size,30);assert(!records.some(r=>r.opportunityType==='RA'||r.jobIds?.length));});
test('public material payload omits internal collection steps and resolves every field source',()=>{const text=JSON.stringify(raw);for(const term of ['verificationMethod','fieldEvidence','web.run','抓取','/workspace/','integrationBlocker'])assert(!text.includes(term));for(const record of records){for(const requirement of record.requirements)assert(requirement.sources.length);const h=renderRecordSummary('material',record,catalog).html;assert(!h.includes('[object Object]'));for(const unknown of record.unknowns)assert(h.includes(unknown.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')));}});
test('invalid, orphan, duplicate, insecure or RA-linked material entries fail closed',()=>{const one=raw.records[0];for(const record of [{...one,routeIds:['missing']},{...one,institution:'Wrong school'},{...one,jobIds:['job']},{...one,opportunityType:'RA'},{...one,sourceIds:['missing']},{...one,requirements:[{text:'No source',requirementStatus:'required',sourceIds:[]}]}])assert.equal(normalizeMaterialSupplement({...raw,records:[record]},catalog).length,0);assert.equal(normalizeMaterialSupplement({...raw,records:[one,one]},catalog).length,1);assert.throws(()=>normalizeMaterialSupplement({...raw,sources:[{...raw.sources[0],url:'javascript:bad'}]},catalog));assert.throws(()=>normalizeMaterialSupplement({records:[]},catalog));});
