import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
// Read shipped fixtures locally; assertions expose only aggregate counts and labels.
class Element{constructor(){this.value='';this.hidden=false;this.innerHTML='';this.textContent='';this.listeners={};this.attrs={};this.open=false;this.classList={toggle(){}};}addEventListener(k,f){this.listeners[k]=f}setAttribute(k,v){this.attrs[k]=v}removeAttribute(k){delete this.attrs[k]}focus(){document.activeElement=this}showModal(){this.open=true}close(){this.open=false}}
const nodes=new Map();const el=s=>{if(!nodes.has(s))nodes.set(s,new Element());return nodes.get(s)};const events={};const navigation={};
globalThis.document={querySelector:el,querySelectorAll:()=>[],getElementById:id=>el('#'+id),addEventListener:(k,f)=>events[k]=f,activeElement:{tagName:'BODY'}};globalThis.window={addEventListener:(k,f)=>navigation[k]=f};globalThis.location={hash:''};
globalThis.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(url,'utf8'))});
await import('../assets/app.js');await new Promise(r=>setImmediate(r));const view=name=>{location.hash='#'+name;navigation.hashchange()};
const change=(name,value)=>{el('#'+name+'-filter').value=value;el('#'+name+'-filter').listeners.change({target:el('#'+name+'-filter')})};
test('real app loads fourteen material groups while preserving opportunity and experience counts',()=>{assert.equal(el('#result-count').textContent,'48 条机会 · 32 位导师');view('materials');assert.equal(el('#result-count').textContent,'14 组材料要求');assert.equal((el('#view-content').innerHTML.match(/class="route-card"/g)||[]).length,14);assert(!el('#view-content').innerHTML.includes('补充材料资料暂未载入'));assert(!el('#view-content').innerHTML.includes('仅覆盖西湖'));assert(!el('#view-content').innerHTML.includes('target="_blank"'));view('experiences');assert.equal(el('#result-count').textContent,'21 条申请经验');});
test('material filters keep campus and degree scopes separate and never invent RA materials',()=>{view('materials');change('institution','HKUST(GZ)');assert.equal(el('#result-count').textContent,'2 组材料要求');change('opportunity','PhD');assert.equal(el('#result-count').textContent,'1 组材料要求');assert(el('#view-content').innerHTML.includes('hkust-gz-phd-materials'));assert(!el('#view-content').innerHTML.includes('hkust-gz-rbm-materials'));el('#reset-filters').listeners.click();assert(!el('#opportunity-filter').innerHTML.includes('value="RA"'));change('opportunity','RA');assert.equal(el('#result-count').textContent,'14 组材料要求');assert.equal(el('#opportunity-filter').value,'');el('#reset-filters').listeners.click();assert.equal(el('#result-count').textContent,'14 组材料要求');});

test('each page shows only applicable controls and keeps its own choices',()=>{view('advisors');el('#reset-filters').listeners.click();change('institution','PolyU');change('rank','associate');change('opportunity','RA');change('opening','explicit');assert.equal(el('#result-count').textContent,'2 条机会 · 1 位导师');view('materials');el('#reset-filters').listeners.click();assert.equal(el('#result-count').textContent,'14 组材料要求');assert.equal(el('#institution-filter').value,'');assert.equal(el('#opportunity-filter').value,'');for(const id of ['rank','topic','opening'])assert(el('#'+id+'-filter-label').hidden);assert(!el('#institution-filter-label').hidden);assert(!el('#opportunity-filter-label').hidden);assert(!el('.search-surface').hidden);assert.equal(el('#opportunity-filter-name').textContent,'适用学位');change('institution','HKU');assert.equal(el('#result-count').textContent,'1 组材料要求');view('deadlines');assert(!el('#institution-filter-label').hidden);for(const id of ['rank','topic','opening','opportunity'])assert(el('#'+id+'-filter-label').hidden);assert(el('.search-surface').hidden);const dates=el('#result-count').textContent;change('rank','unknown');assert.equal(el('#result-count').textContent,dates);view('routes');assert.equal(el('#result-count').textContent,'27 个学位项目');for(const id of ['rank','topic','opening'])assert(el('#'+id+'-filter-label').hidden);assert.equal(el('#opportunity-filter-name').textContent,'学位类型');view('materials');assert.equal(el('#institution-filter').value,'HKU');assert.equal(el('#result-count').textContent,'1 组材料要求');el('#reset-filters').listeners.click();view('advisors');assert.equal(el('#institution-filter').value,'PolyU');assert.equal(el('#rank-filter').value,'associate');assert.equal(el('#opportunity-filter').value,'RA');assert.equal(el('#opening-filter').value,'explicit');assert.equal(el('#result-count').textContent,'2 条机会 · 1 位导师');el('#reset-filters').listeners.click();assert.equal(el('#result-count').textContent,'48 条机会 · 32 位导师');});
test('material search and reset do not mutate advisor search or rank state',()=>{view('advisors');change('rank','associate');el('#search').value='Pai';el('#search').listeners.input({target:el('#search')});const before=el('#result-count').textContent;view('materials');el('#search').value='推荐';el('#search').listeners.input({target:el('#search')});assert.notEqual(el('#result-count').textContent,'0 组材料要求');el('#reset-filters').listeners.click();assert.equal(el('#search').value,'');view('advisors');assert.equal(el('#search').value,'Pai');assert.equal(el('#rank-filter').value,'associate');assert.equal(el('#result-count').textContent,before);el('#reset-filters').listeners.click();});
