import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {buildOpportunities,filterOpportunities,isVerifiedRaPosition,readerText,isVerifiedRoute} from '../assets/core.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));
test('R2 splits 30 eligible advisors into 44 project-specific opportunities',()=>{const rows=buildOpportunities(catalog);assert.equal(rows.length,44);assert.equal(new Set(rows.map(o=>o.advisorId)).size,30);assert.equal(new Set(rows.map(o=>o.id)).size,44);assert(rows.filter(o=>o.type==='MSc').length===2);assert(rows.every(o=>isVerifiedRoute(catalog.routes.find(r=>r.id===o.routeId))));});
test('generic RA recruitment is never converted to a bachelor-eligible job',()=>{assert(catalog.advisors.some(a=>a.openingDetails.some(x=>x.degree==='RA'&&x.status==='explicit')));assert.equal(filterOpportunities(catalog,{opportunityType:'RA'}).length,0);});
test('RA gates require independent bachelor and current job evidence',()=>{const job={id:'job-1',advisorId:catalog.advisors[0].id,opportunityType:'RA',status:'verified',employmentEligibility:{bachelorEligible:true,noMasterRequired:true,explicitJobRequirement:true,sources:[{url:'https://example.edu/jobs/1',label:'岗位学历要求'}]},currentRecruitment:{status:'open',sources:[{url:'https://example.edu/jobs/1',label:'在招岗位'}]}};assert(isVerifiedRaPosition(job));assert.equal(filterOpportunities({...catalog,raPositions:[job]},{opportunityType:'RA'}).length,1);for(const prop of ['bachelorEligible','noMasterRequired','explicitJobRequirement']){assert(!isVerifiedRaPosition({...job,employmentEligibility:{...job.employmentEligibility,[prop]:null}}));}assert(!isVerifiedRaPosition({...job,currentRecruitment:{...job.currentRecruitment,status:'closed'}}));assert(!isVerifiedRaPosition({...job,employmentEligibility:{...job.employmentEligibility,sources:[]}}));});
test('same advisor has different IDs and recruitment status for each opportunity',()=>{const rows=buildOpportunities(catalog);const multi=rows.find(o=>rows.some(r=>r.advisorId===o.advisorId&&r.type!==o.type));assert(multi);const another=rows.find(r=>r.advisorId===multi.advisorId&&r.type!==multi.type);assert.notEqual(multi.id,another.id);});
test('Fall 2027 zero-opening lab stays searchable but is excluded from explicit-open filter',()=>{const rows=filterOpportunities(catalog,{opportunityType:'MPhil',institution:'HKUST',opening:'explicit'});assert.equal(rows.length,0);const closed=filterOpportunities(catalog,{opportunityType:'MPhil',institution:'HKUST',opening:'closed'});assert.equal(closed.length,1);assert.equal(closed[0].advisorId,'hkust-yajing-shen');const a=catalog.advisors.find(x=>x.id==='hkust-yajing-shen');assert.equal(a.name,'Yajing Shen');assert.equal(a.lab,'Mevita Robotics Lab');assert.equal(a.fall2027OpeningVerified,false);for(const degree of ['MPhil','PhD']){const r=a.openingDetails.find(x=>x.degree===degree);assert.equal(r.status,'closed');assert.equal(r.cycle,'2027 Fall');assert.equal(r.cycle2027FallVerified,true);assert.match(r.summary,/0 名额/);}assert.match(a.openingSummary,/不代表其他轮次或永久/);assert.equal(a.recruitmentReview.previous.checkedDate,'2026-10-01');});
test('named PolyU RA advertisements are reflected in the PI without changing degree intake',()=>{const a=catalog.advisors.find(x=>x.id==='polyu_pai_zheng'),ra=a.openingDetails.find(x=>x.degree==='RA');assert.equal(ra.status,'explicit');assert.equal(ra.cycle2027FallVerified,false);assert.equal(ra.degreeRouteAssociated,null);assert.equal(ra.sources.length,2);assert(ra.sources.every(x=>x.url.startsWith('https://jobs.polyu.edu.hk/job_detail.php?job=')));assert.match(a.openings.ra,/剩余名额未核实/);assert.equal(a.openings.cycle2027,'unknown');assert.equal(a.openingDetails.find(x=>x.degree==='MPhil').status,'unknown');assert.equal(a.recruitmentReview.previous.ra,'not verified');});
test('R2 UI exposes four opportunity types without optional eligibility controls',()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert(!html.includes('eligible-only'));assert(!html.includes('type="checkbox"'));assert(!html.includes('<option value="MRes">'));for(const value of ['RA','MSc','MPhil','PhD'])assert(html.includes(`<option value="${value}">`));assert(html.includes('申请类型'));});
test('reader-facing translations preserve uncertainty instead of implying eligibility',()=>{assert.equal(readerText('not publicly verified'),'未核实公开声明');assert(readerText('Not assessed; degree equivalence, academic results, English, graduation timing, supervisor consent, funding and quotas remain individual checks').includes('需按个人情况核实'));assert.equal(readerText('DualVLN'),'DualVLN');});

test('approved RA file contains exactly two open jobs with no invented deadline time',()=>{const ra=JSON.parse(fs.readFileSync(new URL('../data/ra-positions.json',import.meta.url),'utf8'));assert.equal(ra.raPositions.length,2);assert.deepEqual(ra.raPositions.map(j=>j.jobReference).sort(),['260724022','260907004']);assert(ra.raPositions.every(j=>isVerifiedRaPosition(j)&&j.currentRecruitment.deadlineTime===null));const rows=filterOpportunities({...catalog,raPositions:ra.raPositions},{opportunityType:'RA'});assert.equal(rows.length,2);assert.equal(new Set(rows.map(o=>o.advisorId)).size,1);assert.equal(new Set(rows.map(o=>o.id)).size,2);});
test('daily checks enabled is not a successful run or a new evidence date',()=>{const status=JSON.parse(fs.readFileSync(new URL('../data/update-status.json',import.meta.url),'utf8'));assert.equal(status.dailyChecksEnabled,true);assert.equal(status.firstRunVerified,false);assert.equal(status.lastSuccessfulCheck,null);assert.equal(catalog.metadata.checkedDate,'2026-10-01');});
