import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {profileMap,profileSummary,renderProfile,renderProfileReferences} from '../assets/profiles.js';import {buildOpportunities,safeUrl} from '../assets/core.js';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');const academic=JSON.parse(read('data/catalog.json'));const ra=JSON.parse(read('data/ra-positions.json'));const data={...academic,raPositions:ra.raPositions};const supplement=JSON.parse(read('data/advisor-profiles.json'));const expected=['hku-fu-zhang','hkust-yinghao-xu','cuhk_yunhui_liu','cityu_yuxiang_sun','polyu_weisong_wen'].sort();
test('profile pilot joins exactly five existing advisor IDs and never expands opportunities',()=>{assert.deepEqual(supplement.profiles.map(p=>p.advisorId).sort(),expected);assert.equal(profileMap(supplement,academic.advisors).size,5);const rows=buildOpportunities(data);assert.equal(rows.length,46);assert.equal(new Set(rows.map(o=>o.advisorId)).size,30);assert.equal(rows.filter(o=>o.type==='RA').length,2);assert.equal(academic.advisors.length-expected.length,27);assert.equal(profileMap({profiles:[{advisorId:'orphan'}]},academic.advisors).size,0);});
test('profile evidence remains separate from admission and employment authority',()=>{for(const p of supplement.profiles){for(const key of ['eligibility','routeIds','openingDetails','defaultVisible','raPositions','employmentEligibility'])assert(!(key in p));assert.equal(p.confirmedVacancy,false);assert.equal(p.checkedDate,'2026-10-01');assert(p.unknowns.length);assert(p.representativeWorks.length>=2&&p.representativeWorks.length<=3);}assert.equal(profileSummary(undefined,'既有内容'),'既有内容');assert.equal(renderProfile(undefined),'');});
test('all supplement URLs use HTTPS, with safe external markup and escaped text',()=>{function walk(v){if(!v||typeof v!=='object')return;for(const [k,val]of Object.entries(v)){if(k==='url'){assert.equal(new URL(val).protocol,'https:');assert(safeUrl(val));}else walk(val);}}walk(supplement);const malicious={advisorId:'<img>',overview:{textZh:'<script>alert(1)</script>'},labSnapshot:{resources:[]},representativeWorks:[{title:'<img src=x>',url:'javascript:alert(1)'}],unknowns:['<img>']};const html=renderProfile(malicious)+renderProfileReferences(malicious);assert(!html.includes('<script>'));assert(!html.includes('href="javascript:'));assert(html.includes('&lt;script&gt;'));for(const p of supplement.profiles){const h=renderProfile(p)+renderProfileReferences(p);for(const tag of h.match(/<a\b[^>]*>/g)||[]){assert(tag.includes('target="_blank"'));assert(tag.includes('rel="noopener noreferrer"'));}assert(!h.includes('undefined'));assert(!h.includes('[object Object]'));assert(!h.includes('名额已确认'));}});

test('original eligibility, RA evidence and schedule bytes are unchanged',()=>{
assert.equal(crypto.createHash('sha256').update(read('data/catalog.json')).digest('hex'),'094e513c0a2120bb2bee44efda475e2800537bcba797468add44bf5a479bd605');
assert.equal(crypto.createHash('sha256').update(read('data/ra-positions.json')).digest('hex'),'b5354ece6ee48d205665af699e008e74d51c41ca23000c7fc653eccfc906816e');
assert.equal(crypto.createHash('sha256').update(read('data/update-status.json')).digest('hex'),'b96e217f713537808ee7874c3638ed0e2add57d514b2a23232085dd73d35cad5');
});
