import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeProjectSummaries,renderRecordSummary,filterProjectRoutes} from '../assets/record-summaries.js';
import {isVerifiedRoute} from '../assets/core.js';
const read=name=>JSON.parse(fs.readFileSync(new URL('../data/'+name,import.meta.url),'utf8'));
const catalog=read('catalog.json');const raw=read('project-summaries.json');const summaries=normalizeProjectSummaries(raw,catalog);const joined={...catalog,projectSummaries:summaries};
test('twenty-seven project introductions cover all nine current schools without adding routes',()=>{assert.equal(summaries.size,27);assert.deepEqual([...new Set([...summaries.values()].map(r=>r.institution))].sort(),['CUHK','CUHK-Shenzhen','CityUHK','HKBU','HKU','HKUST','HKUST(GZ)','PolyU','Westlake']);assert.equal(catalog.routes.filter(isVerifiedRoute).length,27);assert.equal(raw.sources.length,62);for(const [id,r]of summaries){const route=catalog.routes.find(x=>x.id===id);assert.equal(r.degree,route.degree);assert.equal(r.institution,route.institution);for(const k of ['status','bachelorEligible','noMasterRequired','noTuimianRequired','routeIds','openingDetails','funding'])assert(!(k in r));}});
test('every project claim has reviewed official sources and source dates are independently retained',()=>{const refs=new Set;for(const r of raw.records){for(const f of [r.overview,r.training,r.bachelorEntry,r.cycle,...r.cautions]){assert(f.text.trim());assert(f.sourceIds.length);for(const id of f.sourceIds){refs.add(id);assert(raw.sources.some(s=>s.id===id));}}assert.equal(r.checkedDate,'2026-10-02');}for(const s of raw.sources){assert(refs.has(s.id));assert(new URL(s.url).hostname.match(/(^|\.)(hkust\.edu\.hk|hku\.hk|cuhk\.edu\.hk|cityu\.edu\.hk|polyu\.edu\.hk|ugc\.edu\.hk|hkbu\.edu\.hk|hkust-gz\.edu\.cn|westlake\.edu\.cn|cuhk\.edu\.cn)$/));assert.equal(s.checkedDate,s.id==='city_steps_20261003'?'2026-10-03':'2026-10-02');}assert.equal(raw.sources.find(s=>s.id==='city_mne_programme').publishedUpdatedDate,'2026-08-12');assert.equal(catalog.metadata.checkedDate,'2026-10-01');});
test('summaries precede original-school links and keep academic, material and calendar navigation',()=>{for(const [id,brief]of summaries){const r=catalog.routes.find(x=>x.id===id);const h=renderRecordSummary('project',r,joined).html;for(const phrase of ['培养与研究简介','怎样培养','本科申请入口','批次边界',brief.overview.text,brief.training.text,'2026-10-02','2026-10-01','不等于免交推荐信'])assert(h.includes(phrase),id+': '+phrase);assert(h.indexOf('培养与研究简介')<h.indexOf('项目概览'));assert(h.indexOf(brief.cycle.text)<h.indexOf('打开官网'));assert(h.indexOf('需要留意')<h.indexOf('打开官网'));assert(!h.includes('培养方向、课程安排与资助详情请查阅'));assert(h.includes('准备材料'));for(const a of h.match(/<a\b[^>]*>/g)||[]){assert(a.includes('target="_blank"'));assert(a.includes('rel="noopener noreferrer"'));}}});
test('unsupported projects retain honest basics and unknown or excluded routes never gain summaries',()=>{const r=catalog.routes.find(isVerifiedRoute);const absent=new Map(summaries);absent.delete(r.id);const h=renderRecordSummary('project',r,{...joined,projectSummaries:absent}).html;assert(!h.includes('培养与研究简介'));assert(h.includes('目前整理了项目基本信息'));for(const route of catalog.routes.filter(x=>!isVerifiedRoute(x)))assert.equal(renderRecordSummary('project',route,joined),null);const fake={...raw,records:[{...raw.records[0],routeId:'HKUST-CSE-PhD-supplement',degree:'PhD'}]};assert.equal(normalizeProjectSummaries(fake,catalog).size,0);});
test('project normalization rejects duplicate, orphan, cross-campus, wrong-degree and unsourced records',()=>{const good=raw.records[0];for(const bad of [{...good,routeId:'orphan'},{...good,institution:'HKUST(GZ)'},{...good,degree:'RA'},{...good,overview:{text:'No source',sourceIds:['missing']}},{...good,cautions:[]},{...good,checkedDate:''}])assert.equal(normalizeProjectSummaries({...raw,records:[bad]},catalog).size,0);assert.equal(normalizeProjectSummaries({...raw,records:[good,good]},catalog).size,1);assert.throws(()=>normalizeProjectSummaries({...raw,sources:[...raw.sources,raw.sources[0]]},catalog));assert.throws(()=>normalizeProjectSummaries({...raw,sources:[{...raw.sources[0],url:'javascript:bad'}]},catalog));});
test('project content is escaped and cannot inject routing or eligibility fields',()=>{const good=raw.records[0];const data={...raw,records:[{...good,overview:{...good.overview,text:'<img onerror="bad">'},status:'verified',openingDetails:{PhD:'guaranteed'},funding:'guaranteed'}]};const map=normalizeProjectSummaries(data,catalog);assert(!('funding' in map.get(good.routeId)));const h=renderRecordSummary('project',catalog.routes.find(r=>r.id===good.routeId),{...catalog,projectSummaries:map}).html;assert(h.includes('&lt;img'));assert(!h.includes('<img'));assert(!h.includes('guaranteed'));});
test('degree-specific distinctions and cycle caveats remain explicit',()=>{assert(summaries.get('HKU-CDS-MPhil').cautions[0].text.includes('不能把 MPhil'));assert(summaries.get('cuhk_mae_rpg-phd').cautions[0].text.includes('非全日制'));assert(summaries.get('polyu_ise_rpg-phd').bachelorEntry.text.includes('三年制'));assert(summaries.get('polyu_ise_rpg-mphil').cycle.text.includes('核读时已过'));for(const id of ['cityu_me_rpg-mphil','cityu_me_rpg-phd'])assert(summaries.get(id).cycle.text.includes('截止为 2026-12-01 23:59'));});

test('intro search finds supported research descriptions without crossing school, degree or eligibility filters',()=>{assert.deepEqual(filterProjectRoutes(joined,{query:'人机共融制造'}).map(r=>r.id),['polyu_ise_rpg-mphil','polyu_ise_rpg-phd']);assert.deepEqual(filterProjectRoutes(joined,{query:'人机共融制造',opportunityType:'PhD'}).map(r=>r.id),['polyu_ise_rpg-phd']);assert.equal(filterProjectRoutes(joined,{query:'人机共融制造',institution:'HKUST'}).length,0);assert.equal(filterProjectRoutes(joined,{query:'人机共融制造',opportunityType:'RA'}).length,0);assert.equal(filterProjectRoutes(joined,{}).length,27);});
