// Historical 5e7cd36 data assertions; current application coverage is tested separately.
import test from 'node:test';import assert from 'node:assert/strict';import fs from './historical-source-fs.mjs';import {rankOf,rankLabels,filterOpportunities,filterRoutes,filterDeadlines,themesFor,buildOpportunities} from '../assets/core.js';
const c=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url)));c.raPositions=JSON.parse(fs.readFileSync(new URL('../data/ra-positions.json',import.meta.url))).raPositions;
test('all 43 recorded titles map conservatively without mutation',()=>{const before=JSON.stringify(c);const counts=c.advisors.reduce((n,a)=>(n[rankOf(a)]=(n[rankOf(a)]||0)+1,n),{});assert.deepEqual(counts,{assistant:25,professor:5,associate:10,unknown:1,other:2});assert.equal(rankOf(c.advisors.find(a=>a.id==='xjtlu-yaran-chen')),'unknown');assert.equal(JSON.stringify(c),before);});
test('research, administrative, chair-only and missing titles cannot enter professoriate buckets',()=>{for(const position of ['Research Assistant Professor','Research Associate Professor','Research Professor'])assert.equal(rankOf({position}),'research');for(const position of ['Chair','Chair Professor','PI','Lecturer','Director','Visiting Professor','Assistant Director'])assert.equal(rankOf({position}),'other');for(const position of ['',undefined,'unverified','Professor / Associate Professor'])assert.equal(rankOf({position}),'unknown');assert.equal(rankOf({position:'Assistant Professor；Assistant Director'}),'assistant');assert.equal(rankOf({position:'Associate Professor / Presidential Young Fellow'}),'associate');});
test('rank is independent of new PI, eligibility, tenure and recruitment',()=>{for(const verified of [true,false])assert.equal(rankOf({position:'Assistant Professor',newPi:{verified}}),'assistant');const before=JSON.stringify(c);for(const rank of Object.keys(rankLabels))filterOpportunities(c,{rank});assert.equal(JSON.stringify(c),before);const rows=buildOpportunities(c);assert.equal(rows.length,59);assert.equal(new Set(rows.map(o=>o.advisorId)).size,41);assert.equal(rows.filter(o=>o.type==='RA').length,2);});
test('rank partitions the same opportunity universe with exact denominators',()=>{const counts={professor:6,associate:16,assistant:35,research:0,other:2,unknown:0};const union=[];for(const [rank,count] of Object.entries(counts)){const rows=filterOpportunities(c,{rank});assert.equal(rows.length,count);for(const o of rows)assert.equal(rankOf(c.advisors.find(a=>a.id===o.advisorId)),rank);union.push(...rows.map(o=>o.id));}assert.equal(new Set(union).size,59);assert.deepEqual(filterOpportunities(c,{rank:''}),filterOpportunities(c));});
test('rank combines with school topic opportunity opening and query on the same advisor',()=>{for(const rank of ['professor','associate','assistant'])for(const institution of ['HKU','HKUST','PolyU'])for(const opportunityType of ['PhD','MPhil','RA']){const filters={rank,institution,opportunityType,topic:'机器人学习',opening:'explicit',query:'robot'};const expected=filterOpportunities(c,{...filters,rank:''}).filter(o=>rankOf(c.advisors.find(a=>a.id===o.advisorId))===rank);assert.deepEqual(filterOpportunities(c,filters),expected);}assert.equal(filterOpportunities(c,{rank:'associate',opportunityType:'RA'}).length,2);assert.equal(filterOpportunities(c,{rank:'assistant',opportunityType:'RA'}).length,0);});
test('rank narrows linked academic paths and deadlines without changing eligibility',()=>{for(const rank of ['professor','associate','assistant','unknown']){const routes=filterRoutes(c,{rank});for(const route of routes)assert(c.advisors.some(a=>a.routeIds.includes(route.id)&&rankOf(a)===rank));const ids=new Set(routes.map(r=>r.id));for(const d of filterDeadlines(c,{rank})){if(d.jobId){assert.equal(rank,'associate');continue;}assert(d.routeIds.some(id=>ids.has(id)));}}});

test('route filtering cannot borrow different advisors for combined conditions or use excluded advisors',()=>{
 const route={id:'r',institution:'U',degree:'PhD',program:'Specific route',status:'verified',bachelorEligible:true,noTuimianRequired:true,noMasterRequired:true};
 const make=(id,extra)=>({id,name:id,institution:'U',position:'Assistant Professor',routeIds:['r'],eligibility:'verified',topics:[],...extra});
 const a=make('Alpha',{topics:['robot learning'],openingDetails:[{degree:'PhD',status:'unknown'}]});
 const b=make('Beta',{topics:['SLAM'],openingDetails:[{degree:'PhD',status:'explicit'}]});
 const fixture={routes:[route],advisors:[a,b]};
 const filters={rank:'assistant',topic:'机器人学习',opening:'explicit'};
 assert.equal(filterRoutes(fixture,filters).length,0);
 assert.equal(filterRoutes(fixture,{rank:'assistant',topic:'机器人学习',query:'Beta'}).length,0);
 a.openingDetails[0].status='explicit';assert.equal(filterRoutes(fixture,filters).length,1);
 a.defaultVisible=false;assert.equal(filterRoutes(fixture,filters).length,0);
 a.defaultVisible=true;a.eligibility='unknown';assert.equal(filterRoutes(fixture,filters).length,0);
 assert.equal(filterRoutes(fixture).length,1);
});
