import test from 'node:test';
import assert from 'node:assert/strict';
import {renderRecordSummary,sourceAttribution} from '../assets/record-summaries.js';
const project={id:'p',program:'Sample MSc',institution:'Example University',degree:'MSc',status:'verified',bachelorEligible:true,noTuimianRequired:true,noMasterRequired:true,eligibilitySummary:'An accredited degree is required',requirements:[{text:'English evidence is required'}],supervisorAssociation:'Supervisor availability must be checked separately',applicationMethod:'Apply through the official form',admissionYear:'Historical cycle',notes:['No individual outcome is promised'],sources:[{url:'https://example.org/program'}]};
const date={id:'d',title:'Sample deadline',institution:'Example University',routeIds:['p'],date:'2027-01-10',timezone:'Asia/Hong_Kong',status:'unknown',note:'Different applicant categories may have different dates',sources:[{url:'https://example.org/deadline'}]};
const material={id:'m',title:'Sample statement',institution:'Example University',routeIds:['p'],requirement:'Submit the statement in English',scope:'One historical batch only',sources:[{url:'https://example.org/materials'}]};
const catalog={metadata:{checkedDate:'2026-10-01'},routes:[project],deadlines:[date],materials:[material]};
test('source attribution on list is text only; official links belong to summary',()=>{const h=sourceAttribution(project);assert(h.includes('example.org'));assert(!h.includes('<a'));const r=renderRecordSummary('project',project,catalog);assert(r.html.includes('target="_blank" rel="noopener noreferrer"'));assert(r.html.indexOf('申请条件')<r.html.indexOf('打开官网'));});
test('project summary retains conditions and links to internal date summaries without eligibility badges',()=>{const r=renderRecordSummary('project',project,catalog);assert.equal(r.label,'项目摘要');for(const text of [project.eligibilitySummary,'English evidence is required',project.supervisorAssociation,project.applicationMethod,project.notes[0],'data-summary-kind="deadline"','data-summary-kind="material"','项目概览','学校','院系','项目名称','学位类型'])assert(r.html.includes(text));assert(!r.html.includes('本科路径已核实'));assert(!r.html.includes('class="badge'));assert(r.html.indexOf('项目概览')<r.html.indexOf('申请条件'));assert(!r.html.includes('已记录学制'));const withDuration=renderRecordSummary('project',{...project,duration:'Source-provided duration'},catalog);assert(withDuration.html.includes('Source-provided duration'));assert.equal(renderRecordSummary('project',{...project,noMasterRequired:false},catalog),null);});
test('deadline summary preserves known date and timezone, leaving missing times unknown',()=>{const h=renderRecordSummary('deadline',date,catalog).html;for(const text of ['2027-01-10','Asia/Hong_Kong','截止时刻</dt><dd>未公布','data-summary-kind="project"','申请系统是否开放和导师名额需要分别确认'])assert(h.includes(text));assert(!h.includes('23:59'));assert(!h.includes('当前已开放'));const missing=renderRecordSummary('deadline',{...date,date:null,timezone:null},catalog).html;assert(missing.includes('截止日期待确认'));assert(missing.includes('时区</dt><dd>未注明'));});
test('material summary preserves scope and requirements rather than manufacturing a complete checklist',()=>{const h=renderRecordSummary('material',material,catalog).html;for(const text of [material.requirement,material.scope,'不代表完整申请清单','data-summary-kind="project"'])assert(h.includes(text));assert(h.indexOf(material.requirement)<h.indexOf('打开官网'));});
test('summary rendering rejects missing records and escapes untrusted text and URLs',()=>{assert.equal(renderRecordSummary('other',project,catalog),null);assert.equal(renderRecordSummary('project',null,catalog),null);const h=renderRecordSummary('material',{...material,title:'<img onerror="bad">',requirement:'<script>bad</script>',sources:[{url:'javascript:alert(1)'}]},catalog).html;assert(h.includes('&lt;img'));assert(h.includes('&lt;script'));assert(!h.includes('<img'));assert(!h.includes('javascript:'));});

test('material requirement statuses and known gaps stay explicit',()=>{const r={...material,summary:'Prepare carefully',requirements:[{kind:'cv',text:'An optional CV',requirementStatus:'optional'},{kind:'references',text:'References only for the scholarship path',requirementStatus:'required_for_hkpfs'},{kind:'researchProposal',text:'The project has no common mandatory format',requirementStatus:'not_specified'}],unknowns:['Exact page count is unconfirmed'],scopeNotes:['One school and cycle only']};const h=renderRecordSummary('material',r,catalog).html;for(const text of ['准备概览','简历 · 选交','HKPFS 申请需要','未明确统一要求',r.unknowns[0],r.scopeNotes[0]])assert(h.includes(text));assert(h.indexOf('仍需确认')<h.indexOf('打开官网'));});
