import {escapeHTML,readerText,buildOpportunities} from '../assets/core.js';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
// DOM-contract tests exercise application rendering without claiming browser layout validation.
class Element{constructor(){this.value='';this.hidden=false;this.innerHTML='';this.textContent='';this.checked=true;this.disabled=false;this.listeners={};this.attrs={};this.dataset={};this.classList={toggle(){}};}addEventListener(e,f){this.listeners[e]=f}setAttribute(k,v){this.attrs[k]=v}removeAttribute(k){delete this.attrs[k]}showModal(){this.open=true}close(){this.open=false}focus(){globalThis.document.activeElement=this}}
const elements=new Map;const el=s=>{if(!elements.has(s))elements.set(s,new Element);return elements.get(s)};const navs=['advisors','routes','deadlines','materials','sources'].map(v=>{let a=new Element;a.dataset.view=v;return a;});const documentListeners={};const windowListeners={};
globalThis.document={querySelector:el,querySelectorAll:s=>s==='[data-view]'?navs:s==='dialog'?[el('#detail-dialog'),el('#compare-dialog')]:[],addEventListener:(n,f)=>documentListeners[n]=f,getElementById:id=>el('#'+id),activeElement:{tagName:'BODY'}};globalThis.window={addEventListener:(n,f)=>windowListeners[n]=f};globalThis.location={hash:''};const academicData=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));const raData=JSON.parse(fs.readFileSync(new URL('../data/ra-positions.json',import.meta.url),'utf8'));const statusData=JSON.parse(fs.readFileSync(new URL('../data/update-status.json',import.meta.url),'utf8'));const data={...academicData,raPositions:raData.raPositions};globalThis.fetch=async url=>({ok:true,json:async()=>new URL(url).pathname.endsWith('advisor-profiles.json')?JSON.parse(fs.readFileSync(new URL('../data/advisor-profiles.json',import.meta.url),'utf8')):String(url).endsWith('ra-positions.json')?raData:String(url).endsWith('update-status.json')?statusData:academicData});const opportunities=buildOpportunities(data);await import('../assets/app.js');await new Promise(r=>setImmediate(r));
const change=(selector,value)=>{el(selector).value=value;el(selector).listeners.change({target:el(selector)})};const clickData=(key,value)=>documentListeners.click({target:{closest:selector=>selector===`[${key}]`?{dataset:{[key.slice(5).replace(/-([a-z])/g,(_,a)=>a.toUpperCase())]:value}}:null}});const view=name=>{location.hash='#'+name;windowListeners.hashchange();};
test('application initializes real records and readable names',()=>{assert(el('#result-count').textContent.startsWith('46 '));assert(el('#view-content').innerHTML.includes('advisor-card'));assert(!el('#view-content').innerHTML.includes('[object Object]'));});
test('rendered source labels are distinguishable and URLs safe',()=>{view('routes');const html=el('#view-content').innerHTML;assert(html.includes('prog-crs.hkust.edu.hk'));assert(!html.includes('javascript:'));assert(!html.includes('style='));assert(!html.includes('&quot;kind&quot;'));});
test('verified material content and expired scope render',()=>{view('materials');const html=el('#view-content').innerHTML;assert(html.includes('至少 2'));assert(html.includes('须使用英文'));assert(html.includes('已截止'));});
test('deadlines preserve dates, expired and unknown distinctions',()=>{view('deadlines');const html=el('#view-content').innerHTML;assert(html.includes('此轮已截止'));assert(html.includes('06.01'));assert(html.includes('开放状态待核'));});
test('source page distinguishes enabled checks from a not-yet-verified first run',()=>{view('sources');assert(el('#view-content').innerHTML.includes('每日检查已启用 · 首轮待验证'));assert(el('.search-surface').hidden);view('advisors');assert(!el('.search-surface').hidden);});
test('detail renderer includes route and recruitment source citations',()=>{clickData('data-detail','hku-xihui-liu');assert(el('#detail-dialog').open);const html=el('#detail-content').innerHTML;assert(html.includes('2027 Fall'));assert(html.includes('xh-liu.github.io'));assert(html.includes('认可大学'));assert(!html.includes('[object Object]'));assert(!html.includes('style='));clickData('data-close','detail-dialog');assert(!el('#detail-dialog').open);});
test('default results do not expose an eligibility toggle',()=>{view('advisors');assert(!elements.has('#eligible-only'));assert(el('#result-count').textContent.startsWith('46 '));});
test('repeated comparison can add, remove, clear, and show 2 profiles',()=>{const ids=opportunities.slice(0,2).map(o=>o.id);for(const id of ids)clickData('data-compare',id);assert(el('#compare-count').textContent.includes('2 / 3'));el('#compare-open').listeners.click();assert(el('#compare-content').innerHTML.includes('columns-2'));assert(!el('#compare-content').innerHTML.includes('[object Object]'));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();assert(el('#compare-tray').hidden);});
test('empty filter state can reset to real records',()=>{view('advisors');change('#institution-filter','Not a university');assert(el('#view-content').innerHTML.includes('没有同时满足'));clickData('data-reset','');assert(el('#result-count').textContent.startsWith('46 '));});

test('MSc recruitment row appears in advisor detail with its exact statement',()=>{const advisor=data.advisors.find(a=>/navarro/i.test(a.name));assert(advisor?.openings?.msc);clickData('data-detail',advisor.id);const html=el('#detail-content').innerHTML;assert(html.includes('<dt>MSc</dt>'));assert(html.includes(escapeHTML(readerText(advisor.openings.msc))));clickData('data-close','detail-dialog');});
test('MSc recruitment remains a separate row for each compared profile',()=>{el('#compare-clear').listeners.click();const advisor=data.advisors.find(a=>/navarro/i.test(a.name));const selected=opportunities.find(o=>o.advisorId===advisor.id);const other=opportunities.find(o=>o.advisorId!==advisor.id);clickData('data-compare',selected.id);clickData('data-compare',other.id);el('#compare-open').listeners.click();const html=el('#compare-content').innerHTML;assert.equal((html.match(/<dt>MSc<\/dt>/g)||[]).length,2);assert(html.includes(escapeHTML(readerText(advisor.openings.msc))));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();});

test('RA filter gives honest employment-specific empty state',()=>{view('advisors');change('#institution-filter','HKUST');change('#opportunity-filter','RA');assert(el('#result-count').textContent.startsWith('0 '));assert(el('#view-content').innerHTML.includes('暂无已核实本科可任职的 RA 岗位'));el('#reset-filters').listeners.click();assert(el('#result-count').textContent.startsWith('46 '));});
test('one advisor can have two independently compared opportunity types',()=>{el('#compare-clear').listeners.click();const first=opportunities.find(o=>opportunities.some(other=>other.advisorId===o.advisorId&&other.type!==o.type));const second=opportunities.find(o=>o.advisorId===first.advisorId&&o.type!==first.type);clickData('data-compare',first.id);clickData('data-compare',second.id);el('#compare-open').listeners.click();const html=el('#compare-content').innerHTML;assert(html.includes(`opportunity-type">${first.type}`));assert(html.includes(`opportunity-type">${second.type}`));assert(!html.includes('Not assessed;'));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();});
test('opportunity detail shows only its own project path and preserves other recruit statements',()=>{const o=opportunities.find(o=>o.type==='MPhil');clickData('data-detail',o.id);const html=el('#detail-content').innerHTML;assert(html.includes('opportunity-context">MPhil'));assert(html.includes('本科任职条件待核实'));assert(html.includes('<dt>MSc</dt>'));assert(!html.includes('当前岗位 #'));clickData('data-close','detail-dialog');});

test('two independent RA jobs count as two opportunities but one advisor',()=>{view('advisors');el('#reset-filters').listeners.click();change('#opportunity-filter','RA');assert.equal(el('#result-count').textContent,'2 条机会 · 1 位导师');const html=el('#view-content').innerHTML;assert(html.includes('记忆增强 AI agent'));assert(html.includes('双向认知'));const labels=[...html.matchAll(/aria-label="([^"]+)"/g)].map(m=>m[1]);assert.equal(labels.filter(x=>x.includes('#260907004')).length,3);assert.equal(labels.filter(x=>x.includes('#260724022')).length,3);assert.equal(new Set(labels).size,labels.length);el('#reset-filters').listeners.click();});
test('RA detail keeps employment, deadline-time and work-permit limits visible',()=>{const o=opportunities.find(o=>o.type==='RA');clickData('data-detail',o.id);const html=el('#detail-content').innerHTML;assert(html.includes('截止时刻：未公布'));assert(html.includes('工作许可未核实'));assert(html.includes('岗位任职条件'));assert(html.includes('不授予学位录取资格'));assert(!html.includes('本科任职条件已核实'));assert(!html.includes('本科路径已核实'));assert(html.includes('当前岗位 #260907004 的本科任职条件与公开招募已核实'));assert(html.includes('其他 RA 声明仍需逐岗位核实'));assert(!html.includes('未核实；具体任职条件见对应岗位'));assert(!html.includes('23:59'));clickData('data-close','detail-dialog');const academic=opportunities.find(x=>x.advisorId===o.advisorId&&x.type!=='RA');assert(academic);clickData('data-detail',academic.id);const academicHtml=el('#detail-content').innerHTML;assert(!academicHtml.includes('当前岗位 #'));assert(academicHtml.includes('具体任职条件见对应岗位'));clickData('data-close','detail-dialog');});

test('same-advisor RA comparison names both distinct official job references',()=>{el('#compare-clear').listeners.click();const jobs=opportunities.filter(o=>o.type==='RA');for(const job of jobs)clickData('data-compare',job.id);assert(el('#compare-names').textContent.includes('#260907004'));assert(el('#compare-names').textContent.includes('#260724022'));el('#compare-open').listeners.click();const html=el('#compare-content').innerHTML;assert(html.includes('RA · #260907004'));assert(html.includes('RA · #260724022'));assert(html.includes('当前岗位 #260907004 的本科任职条件与公开招募已核实'));assert(html.includes('当前岗位 #260724022 的本科任职条件与公开招募已核实'));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();});

test('RA advisor selection stays on its page and survives project navigation',()=>{view('advisors');el('#reset-filters').listeners.click();change('#opportunity-filter','RA');assert.equal(el('#result-count').textContent,'2 条机会 · 1 位导师');view('routes');assert.equal(el('#opportunity-filter').value,'');assert(el('#rank-filter-label').hidden);assert.equal(el('#result-count').textContent,'27 个学位项目');assert(!el('#view-content').innerHTML.includes('RA 是科研岗位，不是学位项目'));view('advisors');assert.equal(el('#opportunity-filter').value,'RA');assert.equal(el('#result-count').textContent,'2 条机会 · 1 位导师');el('#reset-filters').listeners.click();});


test('all thirty visible profiles render before original opportunity conditions with independent reference notes',()=>{view('advisors');el('#reset-filters').listeners.click();const html=el('#view-content').innerHTML;assert(!html.includes('专业简介待补充'));assert(html.includes('以无人机为主要载体'));for(const id of ['hku-fu-zhang','hkust-yinghao-xu','cuhk_yunhui_liu','cityu_yuxiang_sun','polyu_weisong_wen','hkust-shaojie-shen','hku-xihui-liu','cuhksz-junjie-hu','westlake-peidong-liu','cityu_peng_yin',"hku-jia-pan","hkust-yajing-shen","hkustgz-jun-ma","polyu_david_navarro","cuhk_fei_chen","hkbu_kaiyang_zhou","cuhksz-tinlun-lam","westlake-donglin-wang","westlake-kaicheng-yu","hkustgz-changhao-chen","hkust-qifeng-chen","hku-hongyang-li","polyu_pai_zheng","hkustgz-junwei-liang","westlake-guojun-qi","hkust-ping-tan","hku-yanchao-yang","hku-chen-sun","polyu_bing_wang","hkustgz-qiang-nie"]){clickData('data-detail',id);const detail=el('#detail-content').innerHTML;assert(detail.indexOf('个人职业概况')<detail.indexOf('实验室与研究资源'));assert(detail.indexOf('实验室与研究资源')<detail.indexOf('近期代表成果'));assert(detail.indexOf('近期代表成果')<detail.indexOf('申请路径与条件'));assert(detail.includes('简介参考与待确认信息'));assert(!detail.includes('undefined'));assert(!detail.includes('[object Object]'));assert(!detail.includes('confirmedVacancy'));clickData('data-close','detail-dialog');}});
test('excluded adviser without a supplement retains the honest fallback without joining visible results',()=>{assert(!opportunities.some(o=>o.advisorId==='cuhk_zhongyu_li'));clickData('data-detail','cuhk_zhongyu_li');const h=el('#detail-content').innerHTML;assert(h.includes('专业简介待补充'));assert(h.includes('研究方向与代表工作'));assert(h.includes('<dt>MSc</dt>'));assert(!h.includes('data-profile-advisor'));clickData('data-close','detail-dialog');});
test('public contact-source conflict remains complete and after references without changing recruitment',()=>{const profile=JSON.parse(fs.readFileSync(new URL('../data/advisor-profiles.json',import.meta.url),'utf8')).profiles.find(p=>p.advisorId==='hkust-yinghao-xu');const conflict=profile.unknowns.find(note=>note.includes('来源冲突'));assert(conflict);const contacts=conflict.match(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g)||[];assert(contacts.length>0);clickData('data-detail',profile.advisorId);const h=el('#detail-content').innerHTML;assert(h.includes(escapeHTML(conflict)));for(const contact of contacts)assert(h.includes(escapeHTML(contact)));assert(h.indexOf(escapeHTML(conflict))>h.indexOf('简介参考与待确认信息'));assert(h.includes('MPhil 名额未证实'));clickData('data-close','detail-dialog');});

test('rank UI composes with opportunity and school then fully resets',()=>{view('advisors');el('#reset-filters').listeners.click();change('#rank-filter','associate');assert.equal(el('#result-count').textContent,'15 条机会 · 9 位导师');change('#institution-filter','PolyU');change('#opportunity-filter','RA');assert.equal(el('#result-count').textContent,'2 条机会 · 1 位导师');change('#rank-filter','assistant');assert(el('#result-count').textContent.startsWith('0 '));clickData('data-reset','');assert.equal(el('#rank-filter').value,'');assert.equal(el('#institution-filter').value,'');assert.equal(el('#opportunity-filter').value,'');assert.equal(el('#result-count').textContent,'46 条机会 · 30 位导师');});
test('raw titles remain visible and rank never manufactures a new PI badge',()=>{view('advisors');el('#reset-filters').listeners.click();change('#rank-filter','professor');const html=el('#view-content').innerHTML;assert(html.includes('原职衔：Choh-Ming Li Professor'));assert(html.includes('原职衔：Professor'));assert(!html.includes('undefined'));el('#reset-filters').listeners.click();view('sources');assert(el('#view-content').innerHTML.includes('职级不代表终身教职、指导资格、招生名额或新 PI'));view('advisors');});
test('empty advisor ranks do not affect project results and are restored on return',()=>{for(const rank of ['research','other','unknown']){view('advisors');change('#rank-filter',rank);assert(el('#result-count').textContent.startsWith('0 '));view('routes');assert(el('#rank-filter-label').hidden);assert.equal(el('#result-count').textContent,'27 个学位项目');view('advisors');assert.equal(el('#rank-filter').value,rank);assert(el('#result-count').textContent.startsWith('0 '));el('#reset-filters').listeners.click();assert.equal(el('#rank-filter').value,'');assert.equal(el('#result-count').textContent,'46 条机会 · 30 位导师');}});

test('targeted PI recruitment review date is visible without relabelling the whole profile',()=>{for(const id of ['hkust-yajing-shen','polyu_pai_zheng']){clickData('data-detail',id);const html=el('#detail-content').innerHTML;assert(html.includes('招募复核于 2026-10-02'));assert(html.includes('其他信息沿用原核验日期'));assert(html.includes('核验于 2026-10-01'));assert(html.includes(escapeHTML(readerText(data.advisors.find(a=>a.id===id).recruitmentReview.scope))));clickData('data-close','detail-dialog');}clickData('data-detail','hku-xihui-liu');assert(!el('#detail-content').innerHTML.includes('招募复核于'));clickData('data-close','detail-dialog');});


test('corrected official Chinese name is consistent in cards, search, detail and comparison',()=>{
 view('advisors');el('#reset-filters').listeners.click();
 assert(el('#view-content').innerHTML.includes('于开丞'));assert(!el('#view-content').innerHTML.includes('余开程'));
 el('#search').value='于开丞';el('#search').listeners.input({target:el('#search')});
 assert(el('#result-count').textContent.includes('1 位导师'));assert(el('#view-content').innerHTML.includes('Kaicheng Yu'));assert(!el('#view-content').innerHTML.includes('余开程'));
 clickData('data-detail','westlake-kaicheng-yu');assert(el('#detail-content').innerHTML.includes('于开丞'));assert(!el('#detail-content').innerHTML.includes('余开程'));clickData('data-close','detail-dialog');
 el('#reset-filters').listeners.click();el('#compare-clear').listeners.click();
 const a=opportunities.find(o=>o.advisorId==='westlake-kaicheng-yu');const b=opportunities.find(o=>o.advisorId!==a.advisorId);
 clickData('data-compare',a.id);clickData('data-compare',b.id);el('#compare-open').listeners.click();assert(el('#compare-content').innerHTML.includes('于开丞'));assert(!el('#compare-content').innerHTML.includes('余开程'));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();
});
