import {escapeHTML} from '../assets/core.js';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
// DOM-contract tests exercise application rendering without claiming browser layout validation.
class Element{constructor(){this.value='';this.hidden=false;this.innerHTML='';this.textContent='';this.checked=true;this.disabled=false;this.listeners={};this.attrs={};this.dataset={};this.classList={toggle(){}};}addEventListener(e,f){this.listeners[e]=f}setAttribute(k,v){this.attrs[k]=v}removeAttribute(k){delete this.attrs[k]}showModal(){this.open=true}close(){this.open=false}focus(){globalThis.document.activeElement=this}}
const elements=new Map;const el=s=>{if(!elements.has(s))elements.set(s,new Element);return elements.get(s)};const navs=['advisors','routes','deadlines','materials','sources'].map(v=>{let a=new Element;a.dataset.view=v;return a;});const documentListeners={};const windowListeners={};
globalThis.document={querySelector:el,querySelectorAll:s=>s==='[data-view]'?navs:s==='dialog'?[el('#detail-dialog'),el('#compare-dialog')]:[],addEventListener:(n,f)=>documentListeners[n]=f,getElementById:id=>el('#'+id),activeElement:{tagName:'BODY'}};globalThis.window={addEventListener:(n,f)=>windowListeners[n]=f};globalThis.location={hash:''};const data=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));globalThis.fetch=async()=>({ok:true,json:async()=>data});await import('../assets/app.js');await new Promise(r=>setImmediate(r));
const change=(selector,value)=>{el(selector).value=value;el(selector).listeners.change({target:el(selector)})};const clickData=(key,value)=>documentListeners.click({target:{closest:selector=>selector===`[${key}]`?{dataset:{[key.slice(5).replace(/-([a-z])/g,(_,a)=>a.toUpperCase())]:value}}:null}});const view=name=>{location.hash='#'+name;windowListeners.hashchange();};
test('application initializes real records and readable names',()=>{assert(el('#result-count').textContent.startsWith('30 '));assert(el('#view-content').innerHTML.includes('advisor-card'));assert(!el('#view-content').innerHTML.includes('[object Object]'));});
test('rendered source labels are distinguishable and URLs safe',()=>{view('routes');const html=el('#view-content').innerHTML;assert(html.includes('prog-crs.hkust.edu.hk'));assert(!html.includes('javascript:'));assert(!html.includes('style='));assert(!html.includes('&quot;kind&quot;'));});
test('verified material content and expired scope render',()=>{view('materials');const html=el('#view-content').innerHTML;assert(html.includes('至少 2'));assert(html.includes('须使用英文'));assert(html.includes('已截止'));});
test('deadlines preserve dates, expired and unknown distinctions',()=>{view('deadlines');const html=el('#view-content').innerHTML;assert(html.includes('此轮已截止'));assert(html.includes('06.01'));assert(html.includes('开放状态待核'));});
test('source page explicitly disclaims enabled daily updates',()=>{view('sources');assert(el('#view-content').innerHTML.includes('每日自动更新尚未启用'));assert(el('.search-surface').hidden);view('advisors');assert(!el('.search-surface').hidden);});
test('detail renderer includes route and recruitment source citations',()=>{clickData('data-detail','hku-xihui-liu');assert(el('#detail-dialog').open);const html=el('#detail-content').innerHTML;assert(html.includes('2027 Fall'));assert(html.includes('xh-liu.github.io'));assert(html.includes('认可大学'));assert(!html.includes('[object Object]'));assert(!html.includes('style='));clickData('data-close','detail-dialog');assert(!el('#detail-dialog').open);});
test('route association unknowns cannot become default recommendations',()=>{view('advisors');el('#eligible-only').checked=false;el('#eligible-only').listeners.change({target:el('#eligible-only')});assert(el('#result-count').textContent.startsWith('32 '));el('#reset-filters').listeners.click();assert(el('#result-count').textContent.startsWith('30 '));});
test('repeated comparison can add, remove, clear, and show 2 profiles',()=>{const ids=data.advisors.slice(0,2).map(a=>a.id);for(const id of ids)clickData('data-compare',id);assert(el('#compare-count').textContent.includes('2 / 3'));el('#compare-open').listeners.click();assert(el('#compare-content').innerHTML.includes('columns-2'));assert(!el('#compare-content').innerHTML.includes('[object Object]'));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();assert(el('#compare-tray').hidden);});
test('empty filter state can reset to real records',()=>{view('advisors');change('#institution-filter','Not a university');assert(el('#view-content').innerHTML.includes('没有同时满足'));clickData('data-reset','');assert(el('#result-count').textContent.startsWith('30 '));});

test('MSc recruitment row appears in advisor detail with its exact statement',()=>{const advisor=data.advisors.find(a=>/navarro/i.test(a.name));assert(advisor?.openings?.msc);clickData('data-detail',advisor.id);const html=el('#detail-content').innerHTML;assert(html.includes('<dt>MSc</dt>'));assert(html.includes(escapeHTML(advisor.openings.msc)));clickData('data-close','detail-dialog');});
test('MSc recruitment remains a separate row for each compared profile',()=>{el('#compare-clear').listeners.click();const advisor=data.advisors.find(a=>/navarro/i.test(a.name));const other=data.advisors.find(a=>a.id!==advisor.id);clickData('data-compare',advisor.id);clickData('data-compare',other.id);el('#compare-open').listeners.click();const html=el('#compare-content').innerHTML;assert.equal((html.match(/<dt>MSc<\/dt>/g)||[]).length,2);assert(html.includes(escapeHTML(advisor.openings.msc)));clickData('data-close','compare-dialog');el('#compare-clear').listeners.click();});
