import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=new URL('../',import.meta.url);const appURL=new URL('assets/app.js',root);const app=fs.readFileSync(appURL,'utf8');const html=fs.readFileSync(new URL('index.html',root),'utf8');
function localPath(reference,owner=root){const url=new URL(reference,owner);assert.equal(url.protocol,'file:');return fileURLToPath(new URL(url.pathname,'file://'));}
const version=path=>crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex').slice(0,12);
const imports=[...app.matchAll(/from\s+['"]([^'"]+)['"]/g)].map(m=>new URL(m[1],appURL));
test('HTML entry and module resources exist when resolved by URL pathname',()=>{const refs=[...html.matchAll(/<(?:script|link)\b[^>]*(?:src|href)="([^"]+)"/g)].map(m=>m[1]);assert(refs.length>=3);for(const ref of refs)assert(fs.existsSync(localPath(ref)),ref);for(const url of imports)assert(fs.existsSync(localPath(url)),url.href);});
test('only changed dependencies receive their actual content versions',()=>{for(const name of ['experiences.js','record-summaries.js']){const url=imports.find(url=>url.pathname.endsWith('/'+name));assert(url);assert.equal(url.searchParams.get('v'),version(localPath(url)));}for(const name of ['core.js','profiles.js','material-supplement.js']){const url=imports.find(url=>url.pathname.endsWith('/'+name));assert(url);assert.equal(url.search,'');}});
test('app and stylesheet entry versions match their final bytes after dependency versioning',()=>{for(const name of ['app.js','style.css']){const ref=[...html.matchAll(/(?:src|href)="([^"]+)"/g)].map(m=>m[1]).find(value=>new URL(value,root).pathname.endsWith('/assets/'+name));assert(ref);const url=new URL(ref,root);assert.equal(url.searchParams.get('v'),version(localPath(url)));}});
test('changed experience data is versioned before the application entry',()=>{const ref=app.match(/new URL\('([^']*data\/application-experiences\.json[^']*)'/)?.[1];assert(ref);const url=new URL(ref,appURL);assert(fs.existsSync(localPath(url)));assert.equal(url.searchParams.get('v'),version(localPath(url)));for(const name of ['catalog.json','ra-positions.json','update-status.json','advisor-profiles.json','material-summaries.json'])assert(!app.includes(name+'?v='));});
